// Code generated by ent, DO NOT EDIT.

package oauthpool

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the oauthpool type in the database.
	Label = "oauth_pool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldEgressRouteID holds the string denoting the egress_route_id field in the database.
	FieldEgressRouteID = "egress_route_id"
	// FieldAllowedOrigins holds the string denoting the allowed_origins field in the database.
	FieldAllowedOrigins = "allowed_origins"
	// FieldAllowedModels holds the string denoting the allowed_models field in the database.
	FieldAllowedModels = "allowed_models"
	// FieldActiveCapsuleSetVersion holds the string denoting the active_capsule_set_version field in the database.
	FieldActiveCapsuleSetVersion = "active_capsule_set_version"
	// FieldPreviousCapsuleSetVersion holds the string denoting the previous_capsule_set_version field in the database.
	FieldPreviousCapsuleSetVersion = "previous_capsule_set_version"
	// FieldCompatibilityDigest holds the string denoting the compatibility_digest field in the database.
	FieldCompatibilityDigest = "compatibility_digest"
	// FieldSessionTTLSeconds holds the string denoting the session_ttl_seconds field in the database.
	FieldSessionTTLSeconds = "session_ttl_seconds"
	// FieldShadowStartedAt holds the string denoting the shadow_started_at field in the database.
	FieldShadowStartedAt = "shadow_started_at"
	// FieldShadowQualifiedAt holds the string denoting the shadow_qualified_at field in the database.
	FieldShadowQualifiedAt = "shadow_qualified_at"
	// EdgeEgressRoute holds the string denoting the egress_route edge name in mutations.
	EdgeEgressRoute = "egress_route"
	// EdgeCredentials holds the string denoting the credentials edge name in mutations.
	EdgeCredentials = "credentials"
	// EdgeCapsuleSets holds the string denoting the capsule_sets edge name in mutations.
	EdgeCapsuleSets = "capsule_sets"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// Table holds the table name of the oauthpool in the database.
	Table = "oauth_pools"
	// EgressRouteTable is the table that holds the egress_route relation/edge.
	EgressRouteTable = "oauth_pools"
	// EgressRouteInverseTable is the table name for the Proxy entity.
	// It exists in this package in order to avoid circular dependency with the "proxy" package.
	EgressRouteInverseTable = "proxies"
	// EgressRouteColumn is the table column denoting the egress_route relation/edge.
	EgressRouteColumn = "egress_route_id"
	// CredentialsTable is the table that holds the credentials relation/edge.
	CredentialsTable = "oauth_pool_credentials"
	// CredentialsInverseTable is the table name for the OAuthPoolCredential entity.
	// It exists in this package in order to avoid circular dependency with the "oauthpoolcredential" package.
	CredentialsInverseTable = "oauth_pool_credentials"
	// CredentialsColumn is the table column denoting the credentials relation/edge.
	CredentialsColumn = "pool_id"
	// CapsuleSetsTable is the table that holds the capsule_sets relation/edge.
	CapsuleSetsTable = "oauth_capsule_sets"
	// CapsuleSetsInverseTable is the table name for the OAuthCapsuleSet entity.
	// It exists in this package in order to avoid circular dependency with the "oauthcapsuleset" package.
	CapsuleSetsInverseTable = "oauth_capsule_sets"
	// CapsuleSetsColumn is the table column denoting the capsule_sets relation/edge.
	CapsuleSetsColumn = "pool_id"
	// GroupsTable is the table that holds the groups relation/edge.
	GroupsTable = "groups"
	// GroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupsInverseTable = "groups"
	// GroupsColumn is the table column denoting the groups relation/edge.
	GroupsColumn = "oauth_pool_id"
)

// Columns holds all SQL columns for oauthpool fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldProvider,
	FieldStatus,
	FieldMode,
	FieldEgressRouteID,
	FieldAllowedOrigins,
	FieldAllowedModels,
	FieldActiveCapsuleSetVersion,
	FieldPreviousCapsuleSetVersion,
	FieldCompatibilityDigest,
	FieldSessionTTLSeconds,
	FieldShadowStartedAt,
	FieldShadowQualifiedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/dofastted/claude2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultMode holds the default value on creation for the "mode" field.
	DefaultMode string
	// ModeValidator is a validator for the "mode" field. It is called by the builders before save.
	ModeValidator func(string) error
	// DefaultAllowedOrigins holds the default value on creation for the "allowed_origins" field.
	DefaultAllowedOrigins []string
	// DefaultAllowedModels holds the default value on creation for the "allowed_models" field.
	DefaultAllowedModels []string
	// DefaultActiveCapsuleSetVersion holds the default value on creation for the "active_capsule_set_version" field.
	DefaultActiveCapsuleSetVersion int64
	// DefaultCompatibilityDigest holds the default value on creation for the "compatibility_digest" field.
	DefaultCompatibilityDigest string
	// CompatibilityDigestValidator is a validator for the "compatibility_digest" field. It is called by the builders before save.
	CompatibilityDigestValidator func(string) error
	// DefaultSessionTTLSeconds holds the default value on creation for the "session_ttl_seconds" field.
	DefaultSessionTTLSeconds int
)

// OrderOption defines the ordering options for the OAuthPool queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByEgressRouteID orders the results by the egress_route_id field.
func ByEgressRouteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEgressRouteID, opts...).ToFunc()
}

// ByActiveCapsuleSetVersion orders the results by the active_capsule_set_version field.
func ByActiveCapsuleSetVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveCapsuleSetVersion, opts...).ToFunc()
}

// ByPreviousCapsuleSetVersion orders the results by the previous_capsule_set_version field.
func ByPreviousCapsuleSetVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousCapsuleSetVersion, opts...).ToFunc()
}

// ByCompatibilityDigest orders the results by the compatibility_digest field.
func ByCompatibilityDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompatibilityDigest, opts...).ToFunc()
}

// BySessionTTLSeconds orders the results by the session_ttl_seconds field.
func BySessionTTLSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionTTLSeconds, opts...).ToFunc()
}

// ByShadowStartedAt orders the results by the shadow_started_at field.
func ByShadowStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShadowStartedAt, opts...).ToFunc()
}

// ByShadowQualifiedAt orders the results by the shadow_qualified_at field.
func ByShadowQualifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShadowQualifiedAt, opts...).ToFunc()
}

// ByEgressRouteField orders the results by egress_route field.
func ByEgressRouteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEgressRouteStep(), sql.OrderByField(field, opts...))
	}
}

// ByCredentialsCount orders the results by credentials count.
func ByCredentialsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCredentialsStep(), opts...)
	}
}

// ByCredentials orders the results by credentials terms.
func ByCredentials(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCredentialsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCapsuleSetsCount orders the results by capsule_sets count.
func ByCapsuleSetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCapsuleSetsStep(), opts...)
	}
}

// ByCapsuleSets orders the results by capsule_sets terms.
func ByCapsuleSets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCapsuleSetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEgressRouteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EgressRouteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EgressRouteTable, EgressRouteColumn),
	)
}
func newCredentialsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CredentialsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CredentialsTable, CredentialsColumn),
	)
}
func newCapsuleSetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CapsuleSetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CapsuleSetsTable, CapsuleSetsColumn),
	)
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
	)
}
