// Code generated by ent, DO NOT EDIT.

package oauthpool

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dofastted/claude2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldName, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldProvider, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldStatus, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldMode, v))
}

// EgressRouteID applies equality check predicate on the "egress_route_id" field. It's identical to EgressRouteIDEQ.
func EgressRouteID(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldEgressRouteID, v))
}

// ActiveCapsuleSetVersion applies equality check predicate on the "active_capsule_set_version" field. It's identical to ActiveCapsuleSetVersionEQ.
func ActiveCapsuleSetVersion(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldActiveCapsuleSetVersion, v))
}

// PreviousCapsuleSetVersion applies equality check predicate on the "previous_capsule_set_version" field. It's identical to PreviousCapsuleSetVersionEQ.
func PreviousCapsuleSetVersion(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldPreviousCapsuleSetVersion, v))
}

// CompatibilityDigest applies equality check predicate on the "compatibility_digest" field. It's identical to CompatibilityDigestEQ.
func CompatibilityDigest(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldCompatibilityDigest, v))
}

// SessionTTLSeconds applies equality check predicate on the "session_ttl_seconds" field. It's identical to SessionTTLSecondsEQ.
func SessionTTLSeconds(v int) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldSessionTTLSeconds, v))
}

// ShadowStartedAt applies equality check predicate on the "shadow_started_at" field. It's identical to ShadowStartedAtEQ.
func ShadowStartedAt(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldShadowStartedAt, v))
}

// ShadowQualifiedAt applies equality check predicate on the "shadow_qualified_at" field. It's identical to ShadowQualifiedAtEQ.
func ShadowQualifiedAt(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldShadowQualifiedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContainsFold(FieldName, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContainsFold(FieldProvider, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContainsFold(FieldStatus, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContainsFold(FieldMode, v))
}

// EgressRouteIDEQ applies the EQ predicate on the "egress_route_id" field.
func EgressRouteIDEQ(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldEgressRouteID, v))
}

// EgressRouteIDNEQ applies the NEQ predicate on the "egress_route_id" field.
func EgressRouteIDNEQ(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldEgressRouteID, v))
}

// EgressRouteIDIn applies the In predicate on the "egress_route_id" field.
func EgressRouteIDIn(vs ...int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldEgressRouteID, vs...))
}

// EgressRouteIDNotIn applies the NotIn predicate on the "egress_route_id" field.
func EgressRouteIDNotIn(vs ...int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldEgressRouteID, vs...))
}

// ActiveCapsuleSetVersionEQ applies the EQ predicate on the "active_capsule_set_version" field.
func ActiveCapsuleSetVersionEQ(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldActiveCapsuleSetVersion, v))
}

// ActiveCapsuleSetVersionNEQ applies the NEQ predicate on the "active_capsule_set_version" field.
func ActiveCapsuleSetVersionNEQ(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldActiveCapsuleSetVersion, v))
}

// ActiveCapsuleSetVersionIn applies the In predicate on the "active_capsule_set_version" field.
func ActiveCapsuleSetVersionIn(vs ...int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldActiveCapsuleSetVersion, vs...))
}

// ActiveCapsuleSetVersionNotIn applies the NotIn predicate on the "active_capsule_set_version" field.
func ActiveCapsuleSetVersionNotIn(vs ...int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldActiveCapsuleSetVersion, vs...))
}

// ActiveCapsuleSetVersionGT applies the GT predicate on the "active_capsule_set_version" field.
func ActiveCapsuleSetVersionGT(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldActiveCapsuleSetVersion, v))
}

// ActiveCapsuleSetVersionGTE applies the GTE predicate on the "active_capsule_set_version" field.
func ActiveCapsuleSetVersionGTE(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldActiveCapsuleSetVersion, v))
}

// ActiveCapsuleSetVersionLT applies the LT predicate on the "active_capsule_set_version" field.
func ActiveCapsuleSetVersionLT(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldActiveCapsuleSetVersion, v))
}

// ActiveCapsuleSetVersionLTE applies the LTE predicate on the "active_capsule_set_version" field.
func ActiveCapsuleSetVersionLTE(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldActiveCapsuleSetVersion, v))
}

// PreviousCapsuleSetVersionEQ applies the EQ predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionEQ(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldPreviousCapsuleSetVersion, v))
}

// PreviousCapsuleSetVersionNEQ applies the NEQ predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionNEQ(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldPreviousCapsuleSetVersion, v))
}

// PreviousCapsuleSetVersionIn applies the In predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionIn(vs ...int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldPreviousCapsuleSetVersion, vs...))
}

// PreviousCapsuleSetVersionNotIn applies the NotIn predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionNotIn(vs ...int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldPreviousCapsuleSetVersion, vs...))
}

// PreviousCapsuleSetVersionGT applies the GT predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionGT(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldPreviousCapsuleSetVersion, v))
}

// PreviousCapsuleSetVersionGTE applies the GTE predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionGTE(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldPreviousCapsuleSetVersion, v))
}

// PreviousCapsuleSetVersionLT applies the LT predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionLT(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldPreviousCapsuleSetVersion, v))
}

// PreviousCapsuleSetVersionLTE applies the LTE predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionLTE(v int64) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldPreviousCapsuleSetVersion, v))
}

// PreviousCapsuleSetVersionIsNil applies the IsNil predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionIsNil() predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIsNull(FieldPreviousCapsuleSetVersion))
}

// PreviousCapsuleSetVersionNotNil applies the NotNil predicate on the "previous_capsule_set_version" field.
func PreviousCapsuleSetVersionNotNil() predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotNull(FieldPreviousCapsuleSetVersion))
}

// CompatibilityDigestEQ applies the EQ predicate on the "compatibility_digest" field.
func CompatibilityDigestEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldCompatibilityDigest, v))
}

// CompatibilityDigestNEQ applies the NEQ predicate on the "compatibility_digest" field.
func CompatibilityDigestNEQ(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldCompatibilityDigest, v))
}

// CompatibilityDigestIn applies the In predicate on the "compatibility_digest" field.
func CompatibilityDigestIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldCompatibilityDigest, vs...))
}

// CompatibilityDigestNotIn applies the NotIn predicate on the "compatibility_digest" field.
func CompatibilityDigestNotIn(vs ...string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldCompatibilityDigest, vs...))
}

// CompatibilityDigestGT applies the GT predicate on the "compatibility_digest" field.
func CompatibilityDigestGT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldCompatibilityDigest, v))
}

// CompatibilityDigestGTE applies the GTE predicate on the "compatibility_digest" field.
func CompatibilityDigestGTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldCompatibilityDigest, v))
}

// CompatibilityDigestLT applies the LT predicate on the "compatibility_digest" field.
func CompatibilityDigestLT(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldCompatibilityDigest, v))
}

// CompatibilityDigestLTE applies the LTE predicate on the "compatibility_digest" field.
func CompatibilityDigestLTE(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldCompatibilityDigest, v))
}

// CompatibilityDigestContains applies the Contains predicate on the "compatibility_digest" field.
func CompatibilityDigestContains(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContains(FieldCompatibilityDigest, v))
}

// CompatibilityDigestHasPrefix applies the HasPrefix predicate on the "compatibility_digest" field.
func CompatibilityDigestHasPrefix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasPrefix(FieldCompatibilityDigest, v))
}

// CompatibilityDigestHasSuffix applies the HasSuffix predicate on the "compatibility_digest" field.
func CompatibilityDigestHasSuffix(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldHasSuffix(FieldCompatibilityDigest, v))
}

// CompatibilityDigestEqualFold applies the EqualFold predicate on the "compatibility_digest" field.
func CompatibilityDigestEqualFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEqualFold(FieldCompatibilityDigest, v))
}

// CompatibilityDigestContainsFold applies the ContainsFold predicate on the "compatibility_digest" field.
func CompatibilityDigestContainsFold(v string) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldContainsFold(FieldCompatibilityDigest, v))
}

// SessionTTLSecondsEQ applies the EQ predicate on the "session_ttl_seconds" field.
func SessionTTLSecondsEQ(v int) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldSessionTTLSeconds, v))
}

// SessionTTLSecondsNEQ applies the NEQ predicate on the "session_ttl_seconds" field.
func SessionTTLSecondsNEQ(v int) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldSessionTTLSeconds, v))
}

// SessionTTLSecondsIn applies the In predicate on the "session_ttl_seconds" field.
func SessionTTLSecondsIn(vs ...int) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldSessionTTLSeconds, vs...))
}

// SessionTTLSecondsNotIn applies the NotIn predicate on the "session_ttl_seconds" field.
func SessionTTLSecondsNotIn(vs ...int) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldSessionTTLSeconds, vs...))
}

// SessionTTLSecondsGT applies the GT predicate on the "session_ttl_seconds" field.
func SessionTTLSecondsGT(v int) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldSessionTTLSeconds, v))
}

// SessionTTLSecondsGTE applies the GTE predicate on the "session_ttl_seconds" field.
func SessionTTLSecondsGTE(v int) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldSessionTTLSeconds, v))
}

// SessionTTLSecondsLT applies the LT predicate on the "session_ttl_seconds" field.
func SessionTTLSecondsLT(v int) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldSessionTTLSeconds, v))
}

// SessionTTLSecondsLTE applies the LTE predicate on the "session_ttl_seconds" field.
func SessionTTLSecondsLTE(v int) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldSessionTTLSeconds, v))
}

// ShadowStartedAtEQ applies the EQ predicate on the "shadow_started_at" field.
func ShadowStartedAtEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldShadowStartedAt, v))
}

// ShadowStartedAtNEQ applies the NEQ predicate on the "shadow_started_at" field.
func ShadowStartedAtNEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldShadowStartedAt, v))
}

// ShadowStartedAtIn applies the In predicate on the "shadow_started_at" field.
func ShadowStartedAtIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldShadowStartedAt, vs...))
}

// ShadowStartedAtNotIn applies the NotIn predicate on the "shadow_started_at" field.
func ShadowStartedAtNotIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldShadowStartedAt, vs...))
}

// ShadowStartedAtGT applies the GT predicate on the "shadow_started_at" field.
func ShadowStartedAtGT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldShadowStartedAt, v))
}

// ShadowStartedAtGTE applies the GTE predicate on the "shadow_started_at" field.
func ShadowStartedAtGTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldShadowStartedAt, v))
}

// ShadowStartedAtLT applies the LT predicate on the "shadow_started_at" field.
func ShadowStartedAtLT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldShadowStartedAt, v))
}

// ShadowStartedAtLTE applies the LTE predicate on the "shadow_started_at" field.
func ShadowStartedAtLTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldShadowStartedAt, v))
}

// ShadowStartedAtIsNil applies the IsNil predicate on the "shadow_started_at" field.
func ShadowStartedAtIsNil() predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIsNull(FieldShadowStartedAt))
}

// ShadowStartedAtNotNil applies the NotNil predicate on the "shadow_started_at" field.
func ShadowStartedAtNotNil() predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotNull(FieldShadowStartedAt))
}

// ShadowQualifiedAtEQ applies the EQ predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldEQ(FieldShadowQualifiedAt, v))
}

// ShadowQualifiedAtNEQ applies the NEQ predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtNEQ(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNEQ(FieldShadowQualifiedAt, v))
}

// ShadowQualifiedAtIn applies the In predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIn(FieldShadowQualifiedAt, vs...))
}

// ShadowQualifiedAtNotIn applies the NotIn predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtNotIn(vs ...time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotIn(FieldShadowQualifiedAt, vs...))
}

// ShadowQualifiedAtGT applies the GT predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtGT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGT(FieldShadowQualifiedAt, v))
}

// ShadowQualifiedAtGTE applies the GTE predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtGTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldGTE(FieldShadowQualifiedAt, v))
}

// ShadowQualifiedAtLT applies the LT predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtLT(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLT(FieldShadowQualifiedAt, v))
}

// ShadowQualifiedAtLTE applies the LTE predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtLTE(v time.Time) predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldLTE(FieldShadowQualifiedAt, v))
}

// ShadowQualifiedAtIsNil applies the IsNil predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtIsNil() predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldIsNull(FieldShadowQualifiedAt))
}

// ShadowQualifiedAtNotNil applies the NotNil predicate on the "shadow_qualified_at" field.
func ShadowQualifiedAtNotNil() predicate.OAuthPool {
	return predicate.OAuthPool(sql.FieldNotNull(FieldShadowQualifiedAt))
}

// HasEgressRoute applies the HasEdge predicate on the "egress_route" edge.
func HasEgressRoute() predicate.OAuthPool {
	return predicate.OAuthPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EgressRouteTable, EgressRouteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEgressRouteWith applies the HasEdge predicate on the "egress_route" edge with a given conditions (other predicates).
func HasEgressRouteWith(preds ...predicate.Proxy) predicate.OAuthPool {
	return predicate.OAuthPool(func(s *sql.Selector) {
		step := newEgressRouteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCredentials applies the HasEdge predicate on the "credentials" edge.
func HasCredentials() predicate.OAuthPool {
	return predicate.OAuthPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CredentialsTable, CredentialsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCredentialsWith applies the HasEdge predicate on the "credentials" edge with a given conditions (other predicates).
func HasCredentialsWith(preds ...predicate.OAuthPoolCredential) predicate.OAuthPool {
	return predicate.OAuthPool(func(s *sql.Selector) {
		step := newCredentialsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCapsuleSets applies the HasEdge predicate on the "capsule_sets" edge.
func HasCapsuleSets() predicate.OAuthPool {
	return predicate.OAuthPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CapsuleSetsTable, CapsuleSetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCapsuleSetsWith applies the HasEdge predicate on the "capsule_sets" edge with a given conditions (other predicates).
func HasCapsuleSetsWith(preds ...predicate.OAuthCapsuleSet) predicate.OAuthPool {
	return predicate.OAuthPool(func(s *sql.Selector) {
		step := newCapsuleSetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.OAuthPool {
	return predicate.OAuthPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.OAuthPool {
	return predicate.OAuthPool(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthPool) predicate.OAuthPool {
	return predicate.OAuthPool(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthPool) predicate.OAuthPool {
	return predicate.OAuthPool(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthPool) predicate.OAuthPool {
	return predicate.OAuthPool(sql.NotPredicates(p))
}
