// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dofastted/claude2api/ent/account"
	"github.com/dofastted/claude2api/ent/oauthpool"
	"github.com/dofastted/claude2api/ent/oauthpoolcredential"
)

// OAuthPoolCredential is the model entity for the OAuthPoolCredential schema.
type OAuthPoolCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PoolID holds the value of the "pool_id" field.
	PoolID int64 `json:"pool_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// CooldownUntil holds the value of the "cooldown_until" field.
	CooldownUntil *time.Time `json:"cooldown_until,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OAuthPoolCredentialQuery when eager-loading is set.
	Edges        OAuthPoolCredentialEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OAuthPoolCredentialEdges holds the relations/edges for other nodes in the graph.
type OAuthPoolCredentialEdges struct {
	// Pool holds the value of the pool edge.
	Pool *OAuthPool `json:"pool,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PoolOrErr returns the Pool value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthPoolCredentialEdges) PoolOrErr() (*OAuthPool, error) {
	if e.Pool != nil {
		return e.Pool, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: oauthpool.Label}
	}
	return nil, &NotLoadedError{edge: "pool"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthPoolCredentialEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthPoolCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthpoolcredential.FieldID, oauthpoolcredential.FieldPoolID, oauthpoolcredential.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case oauthpoolcredential.FieldState:
			values[i] = new(sql.NullString)
		case oauthpoolcredential.FieldCreatedAt, oauthpoolcredential.FieldUpdatedAt, oauthpoolcredential.FieldCooldownUntil:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthPoolCredential fields.
func (_m *OAuthPoolCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthpoolcredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case oauthpoolcredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthpoolcredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oauthpoolcredential.FieldPoolID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pool_id", values[i])
			} else if value.Valid {
				_m.PoolID = value.Int64
			}
		case oauthpoolcredential.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case oauthpoolcredential.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case oauthpoolcredential.FieldCooldownUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_until", values[i])
			} else if value.Valid {
				_m.CooldownUntil = new(time.Time)
				*_m.CooldownUntil = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthPoolCredential.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthPoolCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPool queries the "pool" edge of the OAuthPoolCredential entity.
func (_m *OAuthPoolCredential) QueryPool() *OAuthPoolQuery {
	return NewOAuthPoolCredentialClient(_m.config).QueryPool(_m)
}

// QueryAccount queries the "account" edge of the OAuthPoolCredential entity.
func (_m *OAuthPoolCredential) QueryAccount() *AccountQuery {
	return NewOAuthPoolCredentialClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this OAuthPoolCredential.
// Note that you need to call OAuthPoolCredential.Unwrap() before calling this method if this OAuthPoolCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthPoolCredential) Update() *OAuthPoolCredentialUpdateOne {
	return NewOAuthPoolCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthPoolCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthPoolCredential) Unwrap() *OAuthPoolCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthPoolCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthPoolCredential) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthPoolCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("pool_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PoolID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	if v := _m.CooldownUntil; v != nil {
		builder.WriteString("cooldown_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OAuthPoolCredentials is a parsable slice of OAuthPoolCredential.
type OAuthPoolCredentials []*OAuthPoolCredential
