// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dofastted/claude2api/ent/oauthpool"
	"github.com/dofastted/claude2api/ent/proxy"
)

// OAuthPool is the model entity for the OAuthPool schema.
type OAuthPool struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// EgressRouteID holds the value of the "egress_route_id" field.
	EgressRouteID int64 `json:"egress_route_id,omitempty"`
	// AllowedOrigins holds the value of the "allowed_origins" field.
	AllowedOrigins []string `json:"allowed_origins,omitempty"`
	// AllowedModels holds the value of the "allowed_models" field.
	AllowedModels []string `json:"allowed_models,omitempty"`
	// ActiveCapsuleSetVersion holds the value of the "active_capsule_set_version" field.
	ActiveCapsuleSetVersion int64 `json:"active_capsule_set_version,omitempty"`
	// PreviousCapsuleSetVersion holds the value of the "previous_capsule_set_version" field.
	PreviousCapsuleSetVersion *int64 `json:"previous_capsule_set_version,omitempty"`
	// CompatibilityDigest holds the value of the "compatibility_digest" field.
	CompatibilityDigest string `json:"compatibility_digest,omitempty"`
	// SessionTTLSeconds holds the value of the "session_ttl_seconds" field.
	SessionTTLSeconds int `json:"session_ttl_seconds,omitempty"`
	// ShadowStartedAt holds the value of the "shadow_started_at" field.
	ShadowStartedAt *time.Time `json:"shadow_started_at,omitempty"`
	// ShadowQualifiedAt holds the value of the "shadow_qualified_at" field.
	ShadowQualifiedAt *time.Time `json:"shadow_qualified_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OAuthPoolQuery when eager-loading is set.
	Edges        OAuthPoolEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OAuthPoolEdges holds the relations/edges for other nodes in the graph.
type OAuthPoolEdges struct {
	// EgressRoute holds the value of the egress_route edge.
	EgressRoute *Proxy `json:"egress_route,omitempty"`
	// Credentials holds the value of the credentials edge.
	Credentials []*OAuthPoolCredential `json:"credentials,omitempty"`
	// CapsuleSets holds the value of the capsule_sets edge.
	CapsuleSets []*OAuthCapsuleSet `json:"capsule_sets,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// EgressRouteOrErr returns the EgressRoute value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthPoolEdges) EgressRouteOrErr() (*Proxy, error) {
	if e.EgressRoute != nil {
		return e.EgressRoute, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: proxy.Label}
	}
	return nil, &NotLoadedError{edge: "egress_route"}
}

// CredentialsOrErr returns the Credentials value or an error if the edge
// was not loaded in eager-loading.
func (e OAuthPoolEdges) CredentialsOrErr() ([]*OAuthPoolCredential, error) {
	if e.loadedTypes[1] {
		return e.Credentials, nil
	}
	return nil, &NotLoadedError{edge: "credentials"}
}

// CapsuleSetsOrErr returns the CapsuleSets value or an error if the edge
// was not loaded in eager-loading.
func (e OAuthPoolEdges) CapsuleSetsOrErr() ([]*OAuthCapsuleSet, error) {
	if e.loadedTypes[2] {
		return e.CapsuleSets, nil
	}
	return nil, &NotLoadedError{edge: "capsule_sets"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e OAuthPoolEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[3] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthPool) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthpool.FieldAllowedOrigins, oauthpool.FieldAllowedModels:
			values[i] = new([]byte)
		case oauthpool.FieldID, oauthpool.FieldEgressRouteID, oauthpool.FieldActiveCapsuleSetVersion, oauthpool.FieldPreviousCapsuleSetVersion, oauthpool.FieldSessionTTLSeconds:
			values[i] = new(sql.NullInt64)
		case oauthpool.FieldName, oauthpool.FieldProvider, oauthpool.FieldStatus, oauthpool.FieldMode, oauthpool.FieldCompatibilityDigest:
			values[i] = new(sql.NullString)
		case oauthpool.FieldCreatedAt, oauthpool.FieldUpdatedAt, oauthpool.FieldDeletedAt, oauthpool.FieldShadowStartedAt, oauthpool.FieldShadowQualifiedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthPool fields.
func (_m *OAuthPool) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthpool.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case oauthpool.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthpool.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oauthpool.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case oauthpool.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case oauthpool.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case oauthpool.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case oauthpool.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case oauthpool.FieldEgressRouteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field egress_route_id", values[i])
			} else if value.Valid {
				_m.EgressRouteID = value.Int64
			}
		case oauthpool.FieldAllowedOrigins:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_origins", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedOrigins); err != nil {
					return fmt.Errorf("unmarshal field allowed_origins: %w", err)
				}
			}
		case oauthpool.FieldAllowedModels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_models", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedModels); err != nil {
					return fmt.Errorf("unmarshal field allowed_models: %w", err)
				}
			}
		case oauthpool.FieldActiveCapsuleSetVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field active_capsule_set_version", values[i])
			} else if value.Valid {
				_m.ActiveCapsuleSetVersion = value.Int64
			}
		case oauthpool.FieldPreviousCapsuleSetVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field previous_capsule_set_version", values[i])
			} else if value.Valid {
				_m.PreviousCapsuleSetVersion = new(int64)
				*_m.PreviousCapsuleSetVersion = value.Int64
			}
		case oauthpool.FieldCompatibilityDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field compatibility_digest", values[i])
			} else if value.Valid {
				_m.CompatibilityDigest = value.String
			}
		case oauthpool.FieldSessionTTLSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_ttl_seconds", values[i])
			} else if value.Valid {
				_m.SessionTTLSeconds = int(value.Int64)
			}
		case oauthpool.FieldShadowStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field shadow_started_at", values[i])
			} else if value.Valid {
				_m.ShadowStartedAt = new(time.Time)
				*_m.ShadowStartedAt = value.Time
			}
		case oauthpool.FieldShadowQualifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field shadow_qualified_at", values[i])
			} else if value.Valid {
				_m.ShadowQualifiedAt = new(time.Time)
				*_m.ShadowQualifiedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthPool.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthPool) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEgressRoute queries the "egress_route" edge of the OAuthPool entity.
func (_m *OAuthPool) QueryEgressRoute() *ProxyQuery {
	return NewOAuthPoolClient(_m.config).QueryEgressRoute(_m)
}

// QueryCredentials queries the "credentials" edge of the OAuthPool entity.
func (_m *OAuthPool) QueryCredentials() *OAuthPoolCredentialQuery {
	return NewOAuthPoolClient(_m.config).QueryCredentials(_m)
}

// QueryCapsuleSets queries the "capsule_sets" edge of the OAuthPool entity.
func (_m *OAuthPool) QueryCapsuleSets() *OAuthCapsuleSetQuery {
	return NewOAuthPoolClient(_m.config).QueryCapsuleSets(_m)
}

// QueryGroups queries the "groups" edge of the OAuthPool entity.
func (_m *OAuthPool) QueryGroups() *GroupQuery {
	return NewOAuthPoolClient(_m.config).QueryGroups(_m)
}

// Update returns a builder for updating this OAuthPool.
// Note that you need to call OAuthPool.Unwrap() before calling this method if this OAuthPool
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthPool) Update() *OAuthPoolUpdateOne {
	return NewOAuthPoolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthPool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthPool) Unwrap() *OAuthPool {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthPool is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthPool) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthPool(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("egress_route_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EgressRouteID))
	builder.WriteString(", ")
	builder.WriteString("allowed_origins=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedOrigins))
	builder.WriteString(", ")
	builder.WriteString("allowed_models=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedModels))
	builder.WriteString(", ")
	builder.WriteString("active_capsule_set_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActiveCapsuleSetVersion))
	builder.WriteString(", ")
	if v := _m.PreviousCapsuleSetVersion; v != nil {
		builder.WriteString("previous_capsule_set_version=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("compatibility_digest=")
	builder.WriteString(_m.CompatibilityDigest)
	builder.WriteString(", ")
	builder.WriteString("session_ttl_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionTTLSeconds))
	builder.WriteString(", ")
	if v := _m.ShadowStartedAt; v != nil {
		builder.WriteString("shadow_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ShadowQualifiedAt; v != nil {
		builder.WriteString("shadow_qualified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OAuthPools is a parsable slice of OAuthPool.
type OAuthPools []*OAuthPool
