// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dofastted/claude2api/ent/oauthcapsuleset"
	"github.com/dofastted/claude2api/ent/oauthpool"
)

// OAuthCapsuleSetCreate is the builder for creating a OAuthCapsuleSet entity.
type OAuthCapsuleSetCreate struct {
	config
	mutation *OAuthCapsuleSetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthCapsuleSetCreate) SetCreatedAt(v time.Time) *OAuthCapsuleSetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthCapsuleSetCreate) SetNillableCreatedAt(v *time.Time) *OAuthCapsuleSetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthCapsuleSetCreate) SetUpdatedAt(v time.Time) *OAuthCapsuleSetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthCapsuleSetCreate) SetNillableUpdatedAt(v *time.Time) *OAuthCapsuleSetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPoolID sets the "pool_id" field.
func (_c *OAuthCapsuleSetCreate) SetPoolID(v int64) *OAuthCapsuleSetCreate {
	_c.mutation.SetPoolID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *OAuthCapsuleSetCreate) SetVersion(v int64) *OAuthCapsuleSetCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (_c *OAuthCapsuleSetCreate) SetCompatibilityDigest(v string) *OAuthCapsuleSetCreate {
	_c.mutation.SetCompatibilityDigest(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *OAuthCapsuleSetCreate) SetPayload(v map[string]interface{}) *OAuthCapsuleSetCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetPool sets the "pool" edge to the OAuthPool entity.
func (_c *OAuthCapsuleSetCreate) SetPool(v *OAuthPool) *OAuthCapsuleSetCreate {
	return _c.SetPoolID(v.ID)
}

// Mutation returns the OAuthCapsuleSetMutation object of the builder.
func (_c *OAuthCapsuleSetCreate) Mutation() *OAuthCapsuleSetMutation {
	return _c.mutation
}

// Save creates the OAuthCapsuleSet in the database.
func (_c *OAuthCapsuleSetCreate) Save(ctx context.Context) (*OAuthCapsuleSet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthCapsuleSetCreate) SaveX(ctx context.Context) *OAuthCapsuleSet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthCapsuleSetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthCapsuleSetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthCapsuleSetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthcapsuleset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthcapsuleset.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Payload(); !ok {
		v := oauthcapsuleset.DefaultPayload()
		_c.mutation.SetPayload(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthCapsuleSetCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthCapsuleSet.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthCapsuleSet.updated_at"`)}
	}
	if _, ok := _c.mutation.PoolID(); !ok {
		return &ValidationError{Name: "pool_id", err: errors.New(`ent: missing required field "OAuthCapsuleSet.pool_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "OAuthCapsuleSet.version"`)}
	}
	if _, ok := _c.mutation.CompatibilityDigest(); !ok {
		return &ValidationError{Name: "compatibility_digest", err: errors.New(`ent: missing required field "OAuthCapsuleSet.compatibility_digest"`)}
	}
	if v, ok := _c.mutation.CompatibilityDigest(); ok {
		if err := oauthcapsuleset.CompatibilityDigestValidator(v); err != nil {
			return &ValidationError{Name: "compatibility_digest", err: fmt.Errorf(`ent: validator failed for field "OAuthCapsuleSet.compatibility_digest": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "OAuthCapsuleSet.payload"`)}
	}
	if len(_c.mutation.PoolIDs()) == 0 {
		return &ValidationError{Name: "pool", err: errors.New(`ent: missing required edge "OAuthCapsuleSet.pool"`)}
	}
	return nil
}

func (_c *OAuthCapsuleSetCreate) sqlSave(ctx context.Context) (*OAuthCapsuleSet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthCapsuleSetCreate) createSpec() (*OAuthCapsuleSet, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthCapsuleSet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthcapsuleset.Table, sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthcapsuleset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthcapsuleset.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(oauthcapsuleset.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CompatibilityDigest(); ok {
		_spec.SetField(oauthcapsuleset.FieldCompatibilityDigest, field.TypeString, value)
		_node.CompatibilityDigest = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(oauthcapsuleset.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if nodes := _c.mutation.PoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthcapsuleset.PoolTable,
			Columns: []string{oauthcapsuleset.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PoolID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthCapsuleSet.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthCapsuleSetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthCapsuleSetCreate) OnConflict(opts ...sql.ConflictOption) *OAuthCapsuleSetUpsertOne {
	_c.conflict = opts
	return &OAuthCapsuleSetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthCapsuleSet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthCapsuleSetCreate) OnConflictColumns(columns ...string) *OAuthCapsuleSetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthCapsuleSetUpsertOne{
		create: _c,
	}
}

type (
	// OAuthCapsuleSetUpsertOne is the builder for "upsert"-ing
	//  one OAuthCapsuleSet node.
	OAuthCapsuleSetUpsertOne struct {
		create *OAuthCapsuleSetCreate
	}

	// OAuthCapsuleSetUpsert is the "OnConflict" setter.
	OAuthCapsuleSetUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthCapsuleSetUpsert) SetUpdatedAt(v time.Time) *OAuthCapsuleSetUpsert {
	u.Set(oauthcapsuleset.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsert) UpdateUpdatedAt() *OAuthCapsuleSetUpsert {
	u.SetExcluded(oauthcapsuleset.FieldUpdatedAt)
	return u
}

// SetPoolID sets the "pool_id" field.
func (u *OAuthCapsuleSetUpsert) SetPoolID(v int64) *OAuthCapsuleSetUpsert {
	u.Set(oauthcapsuleset.FieldPoolID, v)
	return u
}

// UpdatePoolID sets the "pool_id" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsert) UpdatePoolID() *OAuthCapsuleSetUpsert {
	u.SetExcluded(oauthcapsuleset.FieldPoolID)
	return u
}

// SetVersion sets the "version" field.
func (u *OAuthCapsuleSetUpsert) SetVersion(v int64) *OAuthCapsuleSetUpsert {
	u.Set(oauthcapsuleset.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsert) UpdateVersion() *OAuthCapsuleSetUpsert {
	u.SetExcluded(oauthcapsuleset.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *OAuthCapsuleSetUpsert) AddVersion(v int64) *OAuthCapsuleSetUpsert {
	u.Add(oauthcapsuleset.FieldVersion, v)
	return u
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (u *OAuthCapsuleSetUpsert) SetCompatibilityDigest(v string) *OAuthCapsuleSetUpsert {
	u.Set(oauthcapsuleset.FieldCompatibilityDigest, v)
	return u
}

// UpdateCompatibilityDigest sets the "compatibility_digest" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsert) UpdateCompatibilityDigest() *OAuthCapsuleSetUpsert {
	u.SetExcluded(oauthcapsuleset.FieldCompatibilityDigest)
	return u
}

// SetPayload sets the "payload" field.
func (u *OAuthCapsuleSetUpsert) SetPayload(v map[string]interface{}) *OAuthCapsuleSetUpsert {
	u.Set(oauthcapsuleset.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsert) UpdatePayload() *OAuthCapsuleSetUpsert {
	u.SetExcluded(oauthcapsuleset.FieldPayload)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthCapsuleSet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthCapsuleSetUpsertOne) UpdateNewValues() *OAuthCapsuleSetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthcapsuleset.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthCapsuleSet.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthCapsuleSetUpsertOne) Ignore() *OAuthCapsuleSetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthCapsuleSetUpsertOne) DoNothing() *OAuthCapsuleSetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthCapsuleSetCreate.OnConflict
// documentation for more info.
func (u *OAuthCapsuleSetUpsertOne) Update(set func(*OAuthCapsuleSetUpsert)) *OAuthCapsuleSetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthCapsuleSetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthCapsuleSetUpsertOne) SetUpdatedAt(v time.Time) *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertOne) UpdateUpdatedAt() *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPoolID sets the "pool_id" field.
func (u *OAuthCapsuleSetUpsertOne) SetPoolID(v int64) *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetPoolID(v)
	})
}

// UpdatePoolID sets the "pool_id" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertOne) UpdatePoolID() *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdatePoolID()
	})
}

// SetVersion sets the "version" field.
func (u *OAuthCapsuleSetUpsertOne) SetVersion(v int64) *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *OAuthCapsuleSetUpsertOne) AddVersion(v int64) *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertOne) UpdateVersion() *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdateVersion()
	})
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (u *OAuthCapsuleSetUpsertOne) SetCompatibilityDigest(v string) *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetCompatibilityDigest(v)
	})
}

// UpdateCompatibilityDigest sets the "compatibility_digest" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertOne) UpdateCompatibilityDigest() *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdateCompatibilityDigest()
	})
}

// SetPayload sets the "payload" field.
func (u *OAuthCapsuleSetUpsertOne) SetPayload(v map[string]interface{}) *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertOne) UpdatePayload() *OAuthCapsuleSetUpsertOne {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdatePayload()
	})
}

// Exec executes the query.
func (u *OAuthCapsuleSetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthCapsuleSetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthCapsuleSetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthCapsuleSetUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthCapsuleSetUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthCapsuleSetCreateBulk is the builder for creating many OAuthCapsuleSet entities in bulk.
type OAuthCapsuleSetCreateBulk struct {
	config
	err      error
	builders []*OAuthCapsuleSetCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthCapsuleSet entities in the database.
func (_c *OAuthCapsuleSetCreateBulk) Save(ctx context.Context) ([]*OAuthCapsuleSet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthCapsuleSet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthCapsuleSetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthCapsuleSetCreateBulk) SaveX(ctx context.Context) []*OAuthCapsuleSet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthCapsuleSetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthCapsuleSetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthCapsuleSet.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthCapsuleSetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthCapsuleSetCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthCapsuleSetUpsertBulk {
	_c.conflict = opts
	return &OAuthCapsuleSetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthCapsuleSet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthCapsuleSetCreateBulk) OnConflictColumns(columns ...string) *OAuthCapsuleSetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthCapsuleSetUpsertBulk{
		create: _c,
	}
}

// OAuthCapsuleSetUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthCapsuleSet nodes.
type OAuthCapsuleSetUpsertBulk struct {
	create *OAuthCapsuleSetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthCapsuleSet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthCapsuleSetUpsertBulk) UpdateNewValues() *OAuthCapsuleSetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthcapsuleset.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthCapsuleSet.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthCapsuleSetUpsertBulk) Ignore() *OAuthCapsuleSetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthCapsuleSetUpsertBulk) DoNothing() *OAuthCapsuleSetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthCapsuleSetCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthCapsuleSetUpsertBulk) Update(set func(*OAuthCapsuleSetUpsert)) *OAuthCapsuleSetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthCapsuleSetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthCapsuleSetUpsertBulk) SetUpdatedAt(v time.Time) *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertBulk) UpdateUpdatedAt() *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPoolID sets the "pool_id" field.
func (u *OAuthCapsuleSetUpsertBulk) SetPoolID(v int64) *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetPoolID(v)
	})
}

// UpdatePoolID sets the "pool_id" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertBulk) UpdatePoolID() *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdatePoolID()
	})
}

// SetVersion sets the "version" field.
func (u *OAuthCapsuleSetUpsertBulk) SetVersion(v int64) *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *OAuthCapsuleSetUpsertBulk) AddVersion(v int64) *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertBulk) UpdateVersion() *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdateVersion()
	})
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (u *OAuthCapsuleSetUpsertBulk) SetCompatibilityDigest(v string) *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetCompatibilityDigest(v)
	})
}

// UpdateCompatibilityDigest sets the "compatibility_digest" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertBulk) UpdateCompatibilityDigest() *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdateCompatibilityDigest()
	})
}

// SetPayload sets the "payload" field.
func (u *OAuthCapsuleSetUpsertBulk) SetPayload(v map[string]interface{}) *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *OAuthCapsuleSetUpsertBulk) UpdatePayload() *OAuthCapsuleSetUpsertBulk {
	return u.Update(func(s *OAuthCapsuleSetUpsert) {
		s.UpdatePayload()
	})
}

// Exec executes the query.
func (u *OAuthCapsuleSetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthCapsuleSetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthCapsuleSetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthCapsuleSetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
