// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dofastted/claude2api/ent/oauthpoolcredential"
	"github.com/dofastted/claude2api/ent/predicate"
)

// OAuthPoolCredentialDelete is the builder for deleting a OAuthPoolCredential entity.
type OAuthPoolCredentialDelete struct {
	config
	hooks    []Hook
	mutation *OAuthPoolCredentialMutation
}

// Where appends a list predicates to the OAuthPoolCredentialDelete builder.
func (_d *OAuthPoolCredentialDelete) Where(ps ...predicate.OAuthPoolCredential) *OAuthPoolCredentialDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OAuthPoolCredentialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthPoolCredentialDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OAuthPoolCredentialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauthpoolcredential.Table, sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OAuthPoolCredentialDeleteOne is the builder for deleting a single OAuthPoolCredential entity.
type OAuthPoolCredentialDeleteOne struct {
	_d *OAuthPoolCredentialDelete
}

// Where appends a list predicates to the OAuthPoolCredentialDelete builder.
func (_d *OAuthPoolCredentialDeleteOne) Where(ps ...predicate.OAuthPoolCredential) *OAuthPoolCredentialDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OAuthPoolCredentialDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthpoolcredential.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthPoolCredentialDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
