// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/dofastted/claude2api/ent/group"
	"github.com/dofastted/claude2api/ent/oauthcapsuleset"
	"github.com/dofastted/claude2api/ent/oauthpool"
	"github.com/dofastted/claude2api/ent/oauthpoolcredential"
	"github.com/dofastted/claude2api/ent/predicate"
	"github.com/dofastted/claude2api/ent/proxy"
)

// OAuthPoolUpdate is the builder for updating OAuthPool entities.
type OAuthPoolUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthPoolMutation
}

// Where appends a list predicates to the OAuthPoolUpdate builder.
func (_u *OAuthPoolUpdate) Where(ps ...predicate.OAuthPool) *OAuthPoolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthPoolUpdate) SetUpdatedAt(v time.Time) *OAuthPoolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OAuthPoolUpdate) SetDeletedAt(v time.Time) *OAuthPoolUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableDeletedAt(v *time.Time) *OAuthPoolUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OAuthPoolUpdate) ClearDeletedAt() *OAuthPoolUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthPoolUpdate) SetName(v string) *OAuthPoolUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableName(v *string) *OAuthPoolUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *OAuthPoolUpdate) SetProvider(v string) *OAuthPoolUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableProvider(v *string) *OAuthPoolUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthPoolUpdate) SetStatus(v string) *OAuthPoolUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableStatus(v *string) *OAuthPoolUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *OAuthPoolUpdate) SetMode(v string) *OAuthPoolUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableMode(v *string) *OAuthPoolUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetEgressRouteID sets the "egress_route_id" field.
func (_u *OAuthPoolUpdate) SetEgressRouteID(v int64) *OAuthPoolUpdate {
	_u.mutation.SetEgressRouteID(v)
	return _u
}

// SetNillableEgressRouteID sets the "egress_route_id" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableEgressRouteID(v *int64) *OAuthPoolUpdate {
	if v != nil {
		_u.SetEgressRouteID(*v)
	}
	return _u
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (_u *OAuthPoolUpdate) SetAllowedOrigins(v []string) *OAuthPoolUpdate {
	_u.mutation.SetAllowedOrigins(v)
	return _u
}

// AppendAllowedOrigins appends value to the "allowed_origins" field.
func (_u *OAuthPoolUpdate) AppendAllowedOrigins(v []string) *OAuthPoolUpdate {
	_u.mutation.AppendAllowedOrigins(v)
	return _u
}

// SetAllowedModels sets the "allowed_models" field.
func (_u *OAuthPoolUpdate) SetAllowedModels(v []string) *OAuthPoolUpdate {
	_u.mutation.SetAllowedModels(v)
	return _u
}

// AppendAllowedModels appends value to the "allowed_models" field.
func (_u *OAuthPoolUpdate) AppendAllowedModels(v []string) *OAuthPoolUpdate {
	_u.mutation.AppendAllowedModels(v)
	return _u
}

// SetActiveCapsuleSetVersion sets the "active_capsule_set_version" field.
func (_u *OAuthPoolUpdate) SetActiveCapsuleSetVersion(v int64) *OAuthPoolUpdate {
	_u.mutation.ResetActiveCapsuleSetVersion()
	_u.mutation.SetActiveCapsuleSetVersion(v)
	return _u
}

// SetNillableActiveCapsuleSetVersion sets the "active_capsule_set_version" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableActiveCapsuleSetVersion(v *int64) *OAuthPoolUpdate {
	if v != nil {
		_u.SetActiveCapsuleSetVersion(*v)
	}
	return _u
}

// AddActiveCapsuleSetVersion adds value to the "active_capsule_set_version" field.
func (_u *OAuthPoolUpdate) AddActiveCapsuleSetVersion(v int64) *OAuthPoolUpdate {
	_u.mutation.AddActiveCapsuleSetVersion(v)
	return _u
}

// SetPreviousCapsuleSetVersion sets the "previous_capsule_set_version" field.
func (_u *OAuthPoolUpdate) SetPreviousCapsuleSetVersion(v int64) *OAuthPoolUpdate {
	_u.mutation.ResetPreviousCapsuleSetVersion()
	_u.mutation.SetPreviousCapsuleSetVersion(v)
	return _u
}

// SetNillablePreviousCapsuleSetVersion sets the "previous_capsule_set_version" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillablePreviousCapsuleSetVersion(v *int64) *OAuthPoolUpdate {
	if v != nil {
		_u.SetPreviousCapsuleSetVersion(*v)
	}
	return _u
}

// AddPreviousCapsuleSetVersion adds value to the "previous_capsule_set_version" field.
func (_u *OAuthPoolUpdate) AddPreviousCapsuleSetVersion(v int64) *OAuthPoolUpdate {
	_u.mutation.AddPreviousCapsuleSetVersion(v)
	return _u
}

// ClearPreviousCapsuleSetVersion clears the value of the "previous_capsule_set_version" field.
func (_u *OAuthPoolUpdate) ClearPreviousCapsuleSetVersion() *OAuthPoolUpdate {
	_u.mutation.ClearPreviousCapsuleSetVersion()
	return _u
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (_u *OAuthPoolUpdate) SetCompatibilityDigest(v string) *OAuthPoolUpdate {
	_u.mutation.SetCompatibilityDigest(v)
	return _u
}

// SetNillableCompatibilityDigest sets the "compatibility_digest" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableCompatibilityDigest(v *string) *OAuthPoolUpdate {
	if v != nil {
		_u.SetCompatibilityDigest(*v)
	}
	return _u
}

// SetSessionTTLSeconds sets the "session_ttl_seconds" field.
func (_u *OAuthPoolUpdate) SetSessionTTLSeconds(v int) *OAuthPoolUpdate {
	_u.mutation.ResetSessionTTLSeconds()
	_u.mutation.SetSessionTTLSeconds(v)
	return _u
}

// SetNillableSessionTTLSeconds sets the "session_ttl_seconds" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableSessionTTLSeconds(v *int) *OAuthPoolUpdate {
	if v != nil {
		_u.SetSessionTTLSeconds(*v)
	}
	return _u
}

// AddSessionTTLSeconds adds value to the "session_ttl_seconds" field.
func (_u *OAuthPoolUpdate) AddSessionTTLSeconds(v int) *OAuthPoolUpdate {
	_u.mutation.AddSessionTTLSeconds(v)
	return _u
}

// SetShadowStartedAt sets the "shadow_started_at" field.
func (_u *OAuthPoolUpdate) SetShadowStartedAt(v time.Time) *OAuthPoolUpdate {
	_u.mutation.SetShadowStartedAt(v)
	return _u
}

// SetNillableShadowStartedAt sets the "shadow_started_at" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableShadowStartedAt(v *time.Time) *OAuthPoolUpdate {
	if v != nil {
		_u.SetShadowStartedAt(*v)
	}
	return _u
}

// ClearShadowStartedAt clears the value of the "shadow_started_at" field.
func (_u *OAuthPoolUpdate) ClearShadowStartedAt() *OAuthPoolUpdate {
	_u.mutation.ClearShadowStartedAt()
	return _u
}

// SetShadowQualifiedAt sets the "shadow_qualified_at" field.
func (_u *OAuthPoolUpdate) SetShadowQualifiedAt(v time.Time) *OAuthPoolUpdate {
	_u.mutation.SetShadowQualifiedAt(v)
	return _u
}

// SetNillableShadowQualifiedAt sets the "shadow_qualified_at" field if the given value is not nil.
func (_u *OAuthPoolUpdate) SetNillableShadowQualifiedAt(v *time.Time) *OAuthPoolUpdate {
	if v != nil {
		_u.SetShadowQualifiedAt(*v)
	}
	return _u
}

// ClearShadowQualifiedAt clears the value of the "shadow_qualified_at" field.
func (_u *OAuthPoolUpdate) ClearShadowQualifiedAt() *OAuthPoolUpdate {
	_u.mutation.ClearShadowQualifiedAt()
	return _u
}

// SetEgressRoute sets the "egress_route" edge to the Proxy entity.
func (_u *OAuthPoolUpdate) SetEgressRoute(v *Proxy) *OAuthPoolUpdate {
	return _u.SetEgressRouteID(v.ID)
}

// AddCredentialIDs adds the "credentials" edge to the OAuthPoolCredential entity by IDs.
func (_u *OAuthPoolUpdate) AddCredentialIDs(ids ...int64) *OAuthPoolUpdate {
	_u.mutation.AddCredentialIDs(ids...)
	return _u
}

// AddCredentials adds the "credentials" edges to the OAuthPoolCredential entity.
func (_u *OAuthPoolUpdate) AddCredentials(v ...*OAuthPoolCredential) *OAuthPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCredentialIDs(ids...)
}

// AddCapsuleSetIDs adds the "capsule_sets" edge to the OAuthCapsuleSet entity by IDs.
func (_u *OAuthPoolUpdate) AddCapsuleSetIDs(ids ...int64) *OAuthPoolUpdate {
	_u.mutation.AddCapsuleSetIDs(ids...)
	return _u
}

// AddCapsuleSets adds the "capsule_sets" edges to the OAuthCapsuleSet entity.
func (_u *OAuthPoolUpdate) AddCapsuleSets(v ...*OAuthCapsuleSet) *OAuthPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCapsuleSetIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *OAuthPoolUpdate) AddGroupIDs(ids ...int64) *OAuthPoolUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *OAuthPoolUpdate) AddGroups(v ...*Group) *OAuthPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// Mutation returns the OAuthPoolMutation object of the builder.
func (_u *OAuthPoolUpdate) Mutation() *OAuthPoolMutation {
	return _u.mutation
}

// ClearEgressRoute clears the "egress_route" edge to the Proxy entity.
func (_u *OAuthPoolUpdate) ClearEgressRoute() *OAuthPoolUpdate {
	_u.mutation.ClearEgressRoute()
	return _u
}

// ClearCredentials clears all "credentials" edges to the OAuthPoolCredential entity.
func (_u *OAuthPoolUpdate) ClearCredentials() *OAuthPoolUpdate {
	_u.mutation.ClearCredentials()
	return _u
}

// RemoveCredentialIDs removes the "credentials" edge to OAuthPoolCredential entities by IDs.
func (_u *OAuthPoolUpdate) RemoveCredentialIDs(ids ...int64) *OAuthPoolUpdate {
	_u.mutation.RemoveCredentialIDs(ids...)
	return _u
}

// RemoveCredentials removes "credentials" edges to OAuthPoolCredential entities.
func (_u *OAuthPoolUpdate) RemoveCredentials(v ...*OAuthPoolCredential) *OAuthPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCredentialIDs(ids...)
}

// ClearCapsuleSets clears all "capsule_sets" edges to the OAuthCapsuleSet entity.
func (_u *OAuthPoolUpdate) ClearCapsuleSets() *OAuthPoolUpdate {
	_u.mutation.ClearCapsuleSets()
	return _u
}

// RemoveCapsuleSetIDs removes the "capsule_sets" edge to OAuthCapsuleSet entities by IDs.
func (_u *OAuthPoolUpdate) RemoveCapsuleSetIDs(ids ...int64) *OAuthPoolUpdate {
	_u.mutation.RemoveCapsuleSetIDs(ids...)
	return _u
}

// RemoveCapsuleSets removes "capsule_sets" edges to OAuthCapsuleSet entities.
func (_u *OAuthPoolUpdate) RemoveCapsuleSets(v ...*OAuthCapsuleSet) *OAuthPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCapsuleSetIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *OAuthPoolUpdate) ClearGroups() *OAuthPoolUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *OAuthPoolUpdate) RemoveGroupIDs(ids ...int64) *OAuthPoolUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *OAuthPoolUpdate) RemoveGroups(v ...*Group) *OAuthPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthPoolUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthPoolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthPoolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthPoolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthPoolUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if oauthpool.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized oauthpool.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := oauthpool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthPoolUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthpool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := oauthpool.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthpool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := oauthpool.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompatibilityDigest(); ok {
		if err := oauthpool.CompatibilityDigestValidator(v); err != nil {
			return &ValidationError{Name: "compatibility_digest", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.compatibility_digest": %w`, err)}
		}
	}
	if _u.mutation.EgressRouteCleared() && len(_u.mutation.EgressRouteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthPool.egress_route"`)
	}
	return nil
}

func (_u *OAuthPoolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthpool.Table, oauthpool.Columns, sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthpool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(oauthpool.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(oauthpool.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthpool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(oauthpool.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthpool.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(oauthpool.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AllowedOrigins(); ok {
		_spec.SetField(oauthpool.FieldAllowedOrigins, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedOrigins(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthpool.FieldAllowedOrigins, value)
		})
	}
	if value, ok := _u.mutation.AllowedModels(); ok {
		_spec.SetField(oauthpool.FieldAllowedModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthpool.FieldAllowedModels, value)
		})
	}
	if value, ok := _u.mutation.ActiveCapsuleSetVersion(); ok {
		_spec.SetField(oauthpool.FieldActiveCapsuleSetVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveCapsuleSetVersion(); ok {
		_spec.AddField(oauthpool.FieldActiveCapsuleSetVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PreviousCapsuleSetVersion(); ok {
		_spec.SetField(oauthpool.FieldPreviousCapsuleSetVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPreviousCapsuleSetVersion(); ok {
		_spec.AddField(oauthpool.FieldPreviousCapsuleSetVersion, field.TypeInt64, value)
	}
	if _u.mutation.PreviousCapsuleSetVersionCleared() {
		_spec.ClearField(oauthpool.FieldPreviousCapsuleSetVersion, field.TypeInt64)
	}
	if value, ok := _u.mutation.CompatibilityDigest(); ok {
		_spec.SetField(oauthpool.FieldCompatibilityDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionTTLSeconds(); ok {
		_spec.SetField(oauthpool.FieldSessionTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionTTLSeconds(); ok {
		_spec.AddField(oauthpool.FieldSessionTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ShadowStartedAt(); ok {
		_spec.SetField(oauthpool.FieldShadowStartedAt, field.TypeTime, value)
	}
	if _u.mutation.ShadowStartedAtCleared() {
		_spec.ClearField(oauthpool.FieldShadowStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ShadowQualifiedAt(); ok {
		_spec.SetField(oauthpool.FieldShadowQualifiedAt, field.TypeTime, value)
	}
	if _u.mutation.ShadowQualifiedAtCleared() {
		_spec.ClearField(oauthpool.FieldShadowQualifiedAt, field.TypeTime)
	}
	if _u.mutation.EgressRouteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpool.EgressRouteTable,
			Columns: []string{oauthpool.EgressRouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EgressRouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpool.EgressRouteTable,
			Columns: []string{oauthpool.EgressRouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CredentialsTable,
			Columns: []string{oauthpool.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCredentialsIDs(); len(nodes) > 0 && !_u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CredentialsTable,
			Columns: []string{oauthpool.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CredentialsTable,
			Columns: []string{oauthpool.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CapsuleSetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CapsuleSetsTable,
			Columns: []string{oauthpool.CapsuleSetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCapsuleSetsIDs(); len(nodes) > 0 && !_u.mutation.CapsuleSetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CapsuleSetsTable,
			Columns: []string{oauthpool.CapsuleSetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CapsuleSetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CapsuleSetsTable,
			Columns: []string{oauthpool.CapsuleSetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.GroupsTable,
			Columns: []string{oauthpool.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.GroupsTable,
			Columns: []string{oauthpool.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.GroupsTable,
			Columns: []string{oauthpool.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthpool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthPoolUpdateOne is the builder for updating a single OAuthPool entity.
type OAuthPoolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthPoolMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthPoolUpdateOne) SetUpdatedAt(v time.Time) *OAuthPoolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OAuthPoolUpdateOne) SetDeletedAt(v time.Time) *OAuthPoolUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableDeletedAt(v *time.Time) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OAuthPoolUpdateOne) ClearDeletedAt() *OAuthPoolUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthPoolUpdateOne) SetName(v string) *OAuthPoolUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableName(v *string) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *OAuthPoolUpdateOne) SetProvider(v string) *OAuthPoolUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableProvider(v *string) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthPoolUpdateOne) SetStatus(v string) *OAuthPoolUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableStatus(v *string) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *OAuthPoolUpdateOne) SetMode(v string) *OAuthPoolUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableMode(v *string) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetEgressRouteID sets the "egress_route_id" field.
func (_u *OAuthPoolUpdateOne) SetEgressRouteID(v int64) *OAuthPoolUpdateOne {
	_u.mutation.SetEgressRouteID(v)
	return _u
}

// SetNillableEgressRouteID sets the "egress_route_id" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableEgressRouteID(v *int64) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetEgressRouteID(*v)
	}
	return _u
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (_u *OAuthPoolUpdateOne) SetAllowedOrigins(v []string) *OAuthPoolUpdateOne {
	_u.mutation.SetAllowedOrigins(v)
	return _u
}

// AppendAllowedOrigins appends value to the "allowed_origins" field.
func (_u *OAuthPoolUpdateOne) AppendAllowedOrigins(v []string) *OAuthPoolUpdateOne {
	_u.mutation.AppendAllowedOrigins(v)
	return _u
}

// SetAllowedModels sets the "allowed_models" field.
func (_u *OAuthPoolUpdateOne) SetAllowedModels(v []string) *OAuthPoolUpdateOne {
	_u.mutation.SetAllowedModels(v)
	return _u
}

// AppendAllowedModels appends value to the "allowed_models" field.
func (_u *OAuthPoolUpdateOne) AppendAllowedModels(v []string) *OAuthPoolUpdateOne {
	_u.mutation.AppendAllowedModels(v)
	return _u
}

// SetActiveCapsuleSetVersion sets the "active_capsule_set_version" field.
func (_u *OAuthPoolUpdateOne) SetActiveCapsuleSetVersion(v int64) *OAuthPoolUpdateOne {
	_u.mutation.ResetActiveCapsuleSetVersion()
	_u.mutation.SetActiveCapsuleSetVersion(v)
	return _u
}

// SetNillableActiveCapsuleSetVersion sets the "active_capsule_set_version" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableActiveCapsuleSetVersion(v *int64) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetActiveCapsuleSetVersion(*v)
	}
	return _u
}

// AddActiveCapsuleSetVersion adds value to the "active_capsule_set_version" field.
func (_u *OAuthPoolUpdateOne) AddActiveCapsuleSetVersion(v int64) *OAuthPoolUpdateOne {
	_u.mutation.AddActiveCapsuleSetVersion(v)
	return _u
}

// SetPreviousCapsuleSetVersion sets the "previous_capsule_set_version" field.
func (_u *OAuthPoolUpdateOne) SetPreviousCapsuleSetVersion(v int64) *OAuthPoolUpdateOne {
	_u.mutation.ResetPreviousCapsuleSetVersion()
	_u.mutation.SetPreviousCapsuleSetVersion(v)
	return _u
}

// SetNillablePreviousCapsuleSetVersion sets the "previous_capsule_set_version" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillablePreviousCapsuleSetVersion(v *int64) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetPreviousCapsuleSetVersion(*v)
	}
	return _u
}

// AddPreviousCapsuleSetVersion adds value to the "previous_capsule_set_version" field.
func (_u *OAuthPoolUpdateOne) AddPreviousCapsuleSetVersion(v int64) *OAuthPoolUpdateOne {
	_u.mutation.AddPreviousCapsuleSetVersion(v)
	return _u
}

// ClearPreviousCapsuleSetVersion clears the value of the "previous_capsule_set_version" field.
func (_u *OAuthPoolUpdateOne) ClearPreviousCapsuleSetVersion() *OAuthPoolUpdateOne {
	_u.mutation.ClearPreviousCapsuleSetVersion()
	return _u
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (_u *OAuthPoolUpdateOne) SetCompatibilityDigest(v string) *OAuthPoolUpdateOne {
	_u.mutation.SetCompatibilityDigest(v)
	return _u
}

// SetNillableCompatibilityDigest sets the "compatibility_digest" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableCompatibilityDigest(v *string) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetCompatibilityDigest(*v)
	}
	return _u
}

// SetSessionTTLSeconds sets the "session_ttl_seconds" field.
func (_u *OAuthPoolUpdateOne) SetSessionTTLSeconds(v int) *OAuthPoolUpdateOne {
	_u.mutation.ResetSessionTTLSeconds()
	_u.mutation.SetSessionTTLSeconds(v)
	return _u
}

// SetNillableSessionTTLSeconds sets the "session_ttl_seconds" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableSessionTTLSeconds(v *int) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetSessionTTLSeconds(*v)
	}
	return _u
}

// AddSessionTTLSeconds adds value to the "session_ttl_seconds" field.
func (_u *OAuthPoolUpdateOne) AddSessionTTLSeconds(v int) *OAuthPoolUpdateOne {
	_u.mutation.AddSessionTTLSeconds(v)
	return _u
}

// SetShadowStartedAt sets the "shadow_started_at" field.
func (_u *OAuthPoolUpdateOne) SetShadowStartedAt(v time.Time) *OAuthPoolUpdateOne {
	_u.mutation.SetShadowStartedAt(v)
	return _u
}

// SetNillableShadowStartedAt sets the "shadow_started_at" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableShadowStartedAt(v *time.Time) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetShadowStartedAt(*v)
	}
	return _u
}

// ClearShadowStartedAt clears the value of the "shadow_started_at" field.
func (_u *OAuthPoolUpdateOne) ClearShadowStartedAt() *OAuthPoolUpdateOne {
	_u.mutation.ClearShadowStartedAt()
	return _u
}

// SetShadowQualifiedAt sets the "shadow_qualified_at" field.
func (_u *OAuthPoolUpdateOne) SetShadowQualifiedAt(v time.Time) *OAuthPoolUpdateOne {
	_u.mutation.SetShadowQualifiedAt(v)
	return _u
}

// SetNillableShadowQualifiedAt sets the "shadow_qualified_at" field if the given value is not nil.
func (_u *OAuthPoolUpdateOne) SetNillableShadowQualifiedAt(v *time.Time) *OAuthPoolUpdateOne {
	if v != nil {
		_u.SetShadowQualifiedAt(*v)
	}
	return _u
}

// ClearShadowQualifiedAt clears the value of the "shadow_qualified_at" field.
func (_u *OAuthPoolUpdateOne) ClearShadowQualifiedAt() *OAuthPoolUpdateOne {
	_u.mutation.ClearShadowQualifiedAt()
	return _u
}

// SetEgressRoute sets the "egress_route" edge to the Proxy entity.
func (_u *OAuthPoolUpdateOne) SetEgressRoute(v *Proxy) *OAuthPoolUpdateOne {
	return _u.SetEgressRouteID(v.ID)
}

// AddCredentialIDs adds the "credentials" edge to the OAuthPoolCredential entity by IDs.
func (_u *OAuthPoolUpdateOne) AddCredentialIDs(ids ...int64) *OAuthPoolUpdateOne {
	_u.mutation.AddCredentialIDs(ids...)
	return _u
}

// AddCredentials adds the "credentials" edges to the OAuthPoolCredential entity.
func (_u *OAuthPoolUpdateOne) AddCredentials(v ...*OAuthPoolCredential) *OAuthPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCredentialIDs(ids...)
}

// AddCapsuleSetIDs adds the "capsule_sets" edge to the OAuthCapsuleSet entity by IDs.
func (_u *OAuthPoolUpdateOne) AddCapsuleSetIDs(ids ...int64) *OAuthPoolUpdateOne {
	_u.mutation.AddCapsuleSetIDs(ids...)
	return _u
}

// AddCapsuleSets adds the "capsule_sets" edges to the OAuthCapsuleSet entity.
func (_u *OAuthPoolUpdateOne) AddCapsuleSets(v ...*OAuthCapsuleSet) *OAuthPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCapsuleSetIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *OAuthPoolUpdateOne) AddGroupIDs(ids ...int64) *OAuthPoolUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *OAuthPoolUpdateOne) AddGroups(v ...*Group) *OAuthPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// Mutation returns the OAuthPoolMutation object of the builder.
func (_u *OAuthPoolUpdateOne) Mutation() *OAuthPoolMutation {
	return _u.mutation
}

// ClearEgressRoute clears the "egress_route" edge to the Proxy entity.
func (_u *OAuthPoolUpdateOne) ClearEgressRoute() *OAuthPoolUpdateOne {
	_u.mutation.ClearEgressRoute()
	return _u
}

// ClearCredentials clears all "credentials" edges to the OAuthPoolCredential entity.
func (_u *OAuthPoolUpdateOne) ClearCredentials() *OAuthPoolUpdateOne {
	_u.mutation.ClearCredentials()
	return _u
}

// RemoveCredentialIDs removes the "credentials" edge to OAuthPoolCredential entities by IDs.
func (_u *OAuthPoolUpdateOne) RemoveCredentialIDs(ids ...int64) *OAuthPoolUpdateOne {
	_u.mutation.RemoveCredentialIDs(ids...)
	return _u
}

// RemoveCredentials removes "credentials" edges to OAuthPoolCredential entities.
func (_u *OAuthPoolUpdateOne) RemoveCredentials(v ...*OAuthPoolCredential) *OAuthPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCredentialIDs(ids...)
}

// ClearCapsuleSets clears all "capsule_sets" edges to the OAuthCapsuleSet entity.
func (_u *OAuthPoolUpdateOne) ClearCapsuleSets() *OAuthPoolUpdateOne {
	_u.mutation.ClearCapsuleSets()
	return _u
}

// RemoveCapsuleSetIDs removes the "capsule_sets" edge to OAuthCapsuleSet entities by IDs.
func (_u *OAuthPoolUpdateOne) RemoveCapsuleSetIDs(ids ...int64) *OAuthPoolUpdateOne {
	_u.mutation.RemoveCapsuleSetIDs(ids...)
	return _u
}

// RemoveCapsuleSets removes "capsule_sets" edges to OAuthCapsuleSet entities.
func (_u *OAuthPoolUpdateOne) RemoveCapsuleSets(v ...*OAuthCapsuleSet) *OAuthPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCapsuleSetIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *OAuthPoolUpdateOne) ClearGroups() *OAuthPoolUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *OAuthPoolUpdateOne) RemoveGroupIDs(ids ...int64) *OAuthPoolUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *OAuthPoolUpdateOne) RemoveGroups(v ...*Group) *OAuthPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// Where appends a list predicates to the OAuthPoolUpdate builder.
func (_u *OAuthPoolUpdateOne) Where(ps ...predicate.OAuthPool) *OAuthPoolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthPoolUpdateOne) Select(field string, fields ...string) *OAuthPoolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthPool entity.
func (_u *OAuthPoolUpdateOne) Save(ctx context.Context) (*OAuthPool, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthPoolUpdateOne) SaveX(ctx context.Context) *OAuthPool {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthPoolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthPoolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthPoolUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if oauthpool.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized oauthpool.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := oauthpool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthPoolUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthpool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := oauthpool.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthpool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := oauthpool.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompatibilityDigest(); ok {
		if err := oauthpool.CompatibilityDigestValidator(v); err != nil {
			return &ValidationError{Name: "compatibility_digest", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.compatibility_digest": %w`, err)}
		}
	}
	if _u.mutation.EgressRouteCleared() && len(_u.mutation.EgressRouteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthPool.egress_route"`)
	}
	return nil
}

func (_u *OAuthPoolUpdateOne) sqlSave(ctx context.Context) (_node *OAuthPool, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthpool.Table, oauthpool.Columns, sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthPool.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthpool.FieldID)
		for _, f := range fields {
			if !oauthpool.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthpool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthpool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(oauthpool.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(oauthpool.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthpool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(oauthpool.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthpool.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(oauthpool.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AllowedOrigins(); ok {
		_spec.SetField(oauthpool.FieldAllowedOrigins, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedOrigins(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthpool.FieldAllowedOrigins, value)
		})
	}
	if value, ok := _u.mutation.AllowedModels(); ok {
		_spec.SetField(oauthpool.FieldAllowedModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthpool.FieldAllowedModels, value)
		})
	}
	if value, ok := _u.mutation.ActiveCapsuleSetVersion(); ok {
		_spec.SetField(oauthpool.FieldActiveCapsuleSetVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveCapsuleSetVersion(); ok {
		_spec.AddField(oauthpool.FieldActiveCapsuleSetVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PreviousCapsuleSetVersion(); ok {
		_spec.SetField(oauthpool.FieldPreviousCapsuleSetVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPreviousCapsuleSetVersion(); ok {
		_spec.AddField(oauthpool.FieldPreviousCapsuleSetVersion, field.TypeInt64, value)
	}
	if _u.mutation.PreviousCapsuleSetVersionCleared() {
		_spec.ClearField(oauthpool.FieldPreviousCapsuleSetVersion, field.TypeInt64)
	}
	if value, ok := _u.mutation.CompatibilityDigest(); ok {
		_spec.SetField(oauthpool.FieldCompatibilityDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionTTLSeconds(); ok {
		_spec.SetField(oauthpool.FieldSessionTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionTTLSeconds(); ok {
		_spec.AddField(oauthpool.FieldSessionTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ShadowStartedAt(); ok {
		_spec.SetField(oauthpool.FieldShadowStartedAt, field.TypeTime, value)
	}
	if _u.mutation.ShadowStartedAtCleared() {
		_spec.ClearField(oauthpool.FieldShadowStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ShadowQualifiedAt(); ok {
		_spec.SetField(oauthpool.FieldShadowQualifiedAt, field.TypeTime, value)
	}
	if _u.mutation.ShadowQualifiedAtCleared() {
		_spec.ClearField(oauthpool.FieldShadowQualifiedAt, field.TypeTime)
	}
	if _u.mutation.EgressRouteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpool.EgressRouteTable,
			Columns: []string{oauthpool.EgressRouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EgressRouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpool.EgressRouteTable,
			Columns: []string{oauthpool.EgressRouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CredentialsTable,
			Columns: []string{oauthpool.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCredentialsIDs(); len(nodes) > 0 && !_u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CredentialsTable,
			Columns: []string{oauthpool.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CredentialsTable,
			Columns: []string{oauthpool.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CapsuleSetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CapsuleSetsTable,
			Columns: []string{oauthpool.CapsuleSetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCapsuleSetsIDs(); len(nodes) > 0 && !_u.mutation.CapsuleSetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CapsuleSetsTable,
			Columns: []string{oauthpool.CapsuleSetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CapsuleSetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CapsuleSetsTable,
			Columns: []string{oauthpool.CapsuleSetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.GroupsTable,
			Columns: []string{oauthpool.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.GroupsTable,
			Columns: []string{oauthpool.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.GroupsTable,
			Columns: []string{oauthpool.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthPool{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthpool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
