// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dofastted/claude2api/ent/oauthcapsuleset"
	"github.com/dofastted/claude2api/ent/predicate"
)

// OAuthCapsuleSetDelete is the builder for deleting a OAuthCapsuleSet entity.
type OAuthCapsuleSetDelete struct {
	config
	hooks    []Hook
	mutation *OAuthCapsuleSetMutation
}

// Where appends a list predicates to the OAuthCapsuleSetDelete builder.
func (_d *OAuthCapsuleSetDelete) Where(ps ...predicate.OAuthCapsuleSet) *OAuthCapsuleSetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OAuthCapsuleSetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthCapsuleSetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OAuthCapsuleSetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauthcapsuleset.Table, sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OAuthCapsuleSetDeleteOne is the builder for deleting a single OAuthCapsuleSet entity.
type OAuthCapsuleSetDeleteOne struct {
	_d *OAuthCapsuleSetDelete
}

// Where appends a list predicates to the OAuthCapsuleSetDelete builder.
func (_d *OAuthCapsuleSetDeleteOne) Where(ps ...predicate.OAuthCapsuleSet) *OAuthCapsuleSetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OAuthCapsuleSetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthcapsuleset.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthCapsuleSetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
