// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dofastted/claude2api/ent/oauthcapsuleset"
	"github.com/dofastted/claude2api/ent/oauthpool"
)

// OAuthCapsuleSet is the model entity for the OAuthCapsuleSet schema.
type OAuthCapsuleSet struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PoolID holds the value of the "pool_id" field.
	PoolID int64 `json:"pool_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// CompatibilityDigest holds the value of the "compatibility_digest" field.
	CompatibilityDigest string `json:"compatibility_digest,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OAuthCapsuleSetQuery when eager-loading is set.
	Edges        OAuthCapsuleSetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OAuthCapsuleSetEdges holds the relations/edges for other nodes in the graph.
type OAuthCapsuleSetEdges struct {
	// Pool holds the value of the pool edge.
	Pool *OAuthPool `json:"pool,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PoolOrErr returns the Pool value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthCapsuleSetEdges) PoolOrErr() (*OAuthPool, error) {
	if e.Pool != nil {
		return e.Pool, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: oauthpool.Label}
	}
	return nil, &NotLoadedError{edge: "pool"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthCapsuleSet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthcapsuleset.FieldPayload:
			values[i] = new([]byte)
		case oauthcapsuleset.FieldID, oauthcapsuleset.FieldPoolID, oauthcapsuleset.FieldVersion:
			values[i] = new(sql.NullInt64)
		case oauthcapsuleset.FieldCompatibilityDigest:
			values[i] = new(sql.NullString)
		case oauthcapsuleset.FieldCreatedAt, oauthcapsuleset.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthCapsuleSet fields.
func (_m *OAuthCapsuleSet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthcapsuleset.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case oauthcapsuleset.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthcapsuleset.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oauthcapsuleset.FieldPoolID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pool_id", values[i])
			} else if value.Valid {
				_m.PoolID = value.Int64
			}
		case oauthcapsuleset.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case oauthcapsuleset.FieldCompatibilityDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field compatibility_digest", values[i])
			} else if value.Valid {
				_m.CompatibilityDigest = value.String
			}
		case oauthcapsuleset.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthCapsuleSet.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthCapsuleSet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPool queries the "pool" edge of the OAuthCapsuleSet entity.
func (_m *OAuthCapsuleSet) QueryPool() *OAuthPoolQuery {
	return NewOAuthCapsuleSetClient(_m.config).QueryPool(_m)
}

// Update returns a builder for updating this OAuthCapsuleSet.
// Note that you need to call OAuthCapsuleSet.Unwrap() before calling this method if this OAuthCapsuleSet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthCapsuleSet) Update() *OAuthCapsuleSetUpdateOne {
	return NewOAuthCapsuleSetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthCapsuleSet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthCapsuleSet) Unwrap() *OAuthCapsuleSet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthCapsuleSet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthCapsuleSet) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthCapsuleSet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("pool_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PoolID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("compatibility_digest=")
	builder.WriteString(_m.CompatibilityDigest)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthCapsuleSets is a parsable slice of OAuthCapsuleSet.
type OAuthCapsuleSets []*OAuthCapsuleSet
