// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dofastted/claude2api/ent/group"
	"github.com/dofastted/claude2api/ent/oauthcapsuleset"
	"github.com/dofastted/claude2api/ent/oauthpool"
	"github.com/dofastted/claude2api/ent/oauthpoolcredential"
	"github.com/dofastted/claude2api/ent/predicate"
	"github.com/dofastted/claude2api/ent/proxy"
)

// OAuthPoolQuery is the builder for querying OAuthPool entities.
type OAuthPoolQuery struct {
	config
	ctx             *QueryContext
	order           []oauthpool.OrderOption
	inters          []Interceptor
	predicates      []predicate.OAuthPool
	withEgressRoute *ProxyQuery
	withCredentials *OAuthPoolCredentialQuery
	withCapsuleSets *OAuthCapsuleSetQuery
	withGroups      *GroupQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OAuthPoolQuery builder.
func (_q *OAuthPoolQuery) Where(ps ...predicate.OAuthPool) *OAuthPoolQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *OAuthPoolQuery) Limit(limit int) *OAuthPoolQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *OAuthPoolQuery) Offset(offset int) *OAuthPoolQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *OAuthPoolQuery) Unique(unique bool) *OAuthPoolQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *OAuthPoolQuery) Order(o ...oauthpool.OrderOption) *OAuthPoolQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEgressRoute chains the current query on the "egress_route" edge.
func (_q *OAuthPoolQuery) QueryEgressRoute() *ProxyQuery {
	query := (&ProxyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthpool.Table, oauthpool.FieldID, selector),
			sqlgraph.To(proxy.Table, proxy.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, oauthpool.EgressRouteTable, oauthpool.EgressRouteColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCredentials chains the current query on the "credentials" edge.
func (_q *OAuthPoolQuery) QueryCredentials() *OAuthPoolCredentialQuery {
	query := (&OAuthPoolCredentialClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthpool.Table, oauthpool.FieldID, selector),
			sqlgraph.To(oauthpoolcredential.Table, oauthpoolcredential.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthpool.CredentialsTable, oauthpool.CredentialsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCapsuleSets chains the current query on the "capsule_sets" edge.
func (_q *OAuthPoolQuery) QueryCapsuleSets() *OAuthCapsuleSetQuery {
	query := (&OAuthCapsuleSetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthpool.Table, oauthpool.FieldID, selector),
			sqlgraph.To(oauthcapsuleset.Table, oauthcapsuleset.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthpool.CapsuleSetsTable, oauthpool.CapsuleSetsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroups chains the current query on the "groups" edge.
func (_q *OAuthPoolQuery) QueryGroups() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthpool.Table, oauthpool.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oauthpool.GroupsTable, oauthpool.GroupsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OAuthPool entity from the query.
// Returns a *NotFoundError when no OAuthPool was found.
func (_q *OAuthPoolQuery) First(ctx context.Context) (*OAuthPool, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{oauthpool.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *OAuthPoolQuery) FirstX(ctx context.Context) *OAuthPool {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OAuthPool ID from the query.
// Returns a *NotFoundError when no OAuthPool ID was found.
func (_q *OAuthPoolQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{oauthpool.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *OAuthPoolQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OAuthPool entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OAuthPool entity is found.
// Returns a *NotFoundError when no OAuthPool entities are found.
func (_q *OAuthPoolQuery) Only(ctx context.Context) (*OAuthPool, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{oauthpool.Label}
	default:
		return nil, &NotSingularError{oauthpool.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *OAuthPoolQuery) OnlyX(ctx context.Context) *OAuthPool {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OAuthPool ID in the query.
// Returns a *NotSingularError when more than one OAuthPool ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *OAuthPoolQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{oauthpool.Label}
	default:
		err = &NotSingularError{oauthpool.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *OAuthPoolQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OAuthPools.
func (_q *OAuthPoolQuery) All(ctx context.Context) ([]*OAuthPool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OAuthPool, *OAuthPoolQuery]()
	return withInterceptors[[]*OAuthPool](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *OAuthPoolQuery) AllX(ctx context.Context) []*OAuthPool {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OAuthPool IDs.
func (_q *OAuthPoolQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(oauthpool.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *OAuthPoolQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *OAuthPoolQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*OAuthPoolQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *OAuthPoolQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *OAuthPoolQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *OAuthPoolQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OAuthPoolQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *OAuthPoolQuery) Clone() *OAuthPoolQuery {
	if _q == nil {
		return nil
	}
	return &OAuthPoolQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]oauthpool.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.OAuthPool{}, _q.predicates...),
		withEgressRoute: _q.withEgressRoute.Clone(),
		withCredentials: _q.withCredentials.Clone(),
		withCapsuleSets: _q.withCapsuleSets.Clone(),
		withGroups:      _q.withGroups.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEgressRoute tells the query-builder to eager-load the nodes that are connected to
// the "egress_route" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthPoolQuery) WithEgressRoute(opts ...func(*ProxyQuery)) *OAuthPoolQuery {
	query := (&ProxyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEgressRoute = query
	return _q
}

// WithCredentials tells the query-builder to eager-load the nodes that are connected to
// the "credentials" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthPoolQuery) WithCredentials(opts ...func(*OAuthPoolCredentialQuery)) *OAuthPoolQuery {
	query := (&OAuthPoolCredentialClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCredentials = query
	return _q
}

// WithCapsuleSets tells the query-builder to eager-load the nodes that are connected to
// the "capsule_sets" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthPoolQuery) WithCapsuleSets(opts ...func(*OAuthCapsuleSetQuery)) *OAuthPoolQuery {
	query := (&OAuthCapsuleSetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCapsuleSets = query
	return _q
}

// WithGroups tells the query-builder to eager-load the nodes that are connected to
// the "groups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OAuthPoolQuery) WithGroups(opts ...func(*GroupQuery)) *OAuthPoolQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroups = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OAuthPool.Query().
//		GroupBy(oauthpool.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *OAuthPoolQuery) GroupBy(field string, fields ...string) *OAuthPoolGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OAuthPoolGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = oauthpool.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OAuthPool.Query().
//		Select(oauthpool.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *OAuthPoolQuery) Select(fields ...string) *OAuthPoolSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &OAuthPoolSelect{OAuthPoolQuery: _q}
	sbuild.label = oauthpool.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OAuthPoolSelect configured with the given aggregations.
func (_q *OAuthPoolQuery) Aggregate(fns ...AggregateFunc) *OAuthPoolSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *OAuthPoolQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !oauthpool.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *OAuthPoolQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OAuthPool, error) {
	var (
		nodes       = []*OAuthPool{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withEgressRoute != nil,
			_q.withCredentials != nil,
			_q.withCapsuleSets != nil,
			_q.withGroups != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OAuthPool).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OAuthPool{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEgressRoute; query != nil {
		if err := _q.loadEgressRoute(ctx, query, nodes, nil,
			func(n *OAuthPool, e *Proxy) { n.Edges.EgressRoute = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCredentials; query != nil {
		if err := _q.loadCredentials(ctx, query, nodes,
			func(n *OAuthPool) { n.Edges.Credentials = []*OAuthPoolCredential{} },
			func(n *OAuthPool, e *OAuthPoolCredential) { n.Edges.Credentials = append(n.Edges.Credentials, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCapsuleSets; query != nil {
		if err := _q.loadCapsuleSets(ctx, query, nodes,
			func(n *OAuthPool) { n.Edges.CapsuleSets = []*OAuthCapsuleSet{} },
			func(n *OAuthPool, e *OAuthCapsuleSet) { n.Edges.CapsuleSets = append(n.Edges.CapsuleSets, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroups; query != nil {
		if err := _q.loadGroups(ctx, query, nodes,
			func(n *OAuthPool) { n.Edges.Groups = []*Group{} },
			func(n *OAuthPool, e *Group) { n.Edges.Groups = append(n.Edges.Groups, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *OAuthPoolQuery) loadEgressRoute(ctx context.Context, query *ProxyQuery, nodes []*OAuthPool, init func(*OAuthPool), assign func(*OAuthPool, *Proxy)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*OAuthPool)
	for i := range nodes {
		fk := nodes[i].EgressRouteID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(proxy.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "egress_route_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OAuthPoolQuery) loadCredentials(ctx context.Context, query *OAuthPoolCredentialQuery, nodes []*OAuthPool, init func(*OAuthPool), assign func(*OAuthPool, *OAuthPoolCredential)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthPool)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthpoolcredential.FieldPoolID)
	}
	query.Where(predicate.OAuthPoolCredential(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthpool.CredentialsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PoolID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "pool_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OAuthPoolQuery) loadCapsuleSets(ctx context.Context, query *OAuthCapsuleSetQuery, nodes []*OAuthPool, init func(*OAuthPool), assign func(*OAuthPool, *OAuthCapsuleSet)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthPool)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oauthcapsuleset.FieldPoolID)
	}
	query.Where(predicate.OAuthCapsuleSet(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthpool.CapsuleSetsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PoolID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "pool_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OAuthPoolQuery) loadGroups(ctx context.Context, query *GroupQuery, nodes []*OAuthPool, init func(*OAuthPool), assign func(*OAuthPool, *Group)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*OAuthPool)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(group.FieldOauthPoolID)
	}
	query.Where(predicate.Group(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(oauthpool.GroupsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OauthPoolID
		if fk == nil {
			return fmt.Errorf(`foreign-key "oauth_pool_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "oauth_pool_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *OAuthPoolQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *OAuthPoolQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(oauthpool.Table, oauthpool.Columns, sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthpool.FieldID)
		for i := range fields {
			if fields[i] != oauthpool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withEgressRoute != nil {
			_spec.Node.AddColumnOnce(oauthpool.FieldEgressRouteID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *OAuthPoolQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(oauthpool.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = oauthpool.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *OAuthPoolQuery) ForUpdate(opts ...sql.LockOption) *OAuthPoolQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *OAuthPoolQuery) ForShare(opts ...sql.LockOption) *OAuthPoolQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// OAuthPoolGroupBy is the group-by builder for OAuthPool entities.
type OAuthPoolGroupBy struct {
	selector
	build *OAuthPoolQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *OAuthPoolGroupBy) Aggregate(fns ...AggregateFunc) *OAuthPoolGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *OAuthPoolGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthPoolQuery, *OAuthPoolGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *OAuthPoolGroupBy) sqlScan(ctx context.Context, root *OAuthPoolQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OAuthPoolSelect is the builder for selecting fields of OAuthPool entities.
type OAuthPoolSelect struct {
	*OAuthPoolQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *OAuthPoolSelect) Aggregate(fns ...AggregateFunc) *OAuthPoolSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *OAuthPoolSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthPoolQuery, *OAuthPoolSelect](ctx, _s.OAuthPoolQuery, _s, _s.inters, v)
}

func (_s *OAuthPoolSelect) sqlScan(ctx context.Context, root *OAuthPoolQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
