// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dofastted/claude2api/ent/account"
	"github.com/dofastted/claude2api/ent/oauthpool"
	"github.com/dofastted/claude2api/ent/oauthpoolcredential"
	"github.com/dofastted/claude2api/ent/predicate"
)

// OAuthPoolCredentialUpdate is the builder for updating OAuthPoolCredential entities.
type OAuthPoolCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthPoolCredentialMutation
}

// Where appends a list predicates to the OAuthPoolCredentialUpdate builder.
func (_u *OAuthPoolCredentialUpdate) Where(ps ...predicate.OAuthPoolCredential) *OAuthPoolCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthPoolCredentialUpdate) SetUpdatedAt(v time.Time) *OAuthPoolCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPoolID sets the "pool_id" field.
func (_u *OAuthPoolCredentialUpdate) SetPoolID(v int64) *OAuthPoolCredentialUpdate {
	_u.mutation.SetPoolID(v)
	return _u
}

// SetNillablePoolID sets the "pool_id" field if the given value is not nil.
func (_u *OAuthPoolCredentialUpdate) SetNillablePoolID(v *int64) *OAuthPoolCredentialUpdate {
	if v != nil {
		_u.SetPoolID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OAuthPoolCredentialUpdate) SetAccountID(v int64) *OAuthPoolCredentialUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OAuthPoolCredentialUpdate) SetNillableAccountID(v *int64) *OAuthPoolCredentialUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *OAuthPoolCredentialUpdate) SetState(v string) *OAuthPoolCredentialUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *OAuthPoolCredentialUpdate) SetNillableState(v *string) *OAuthPoolCredentialUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *OAuthPoolCredentialUpdate) SetCooldownUntil(v time.Time) *OAuthPoolCredentialUpdate {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *OAuthPoolCredentialUpdate) SetNillableCooldownUntil(v *time.Time) *OAuthPoolCredentialUpdate {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *OAuthPoolCredentialUpdate) ClearCooldownUntil() *OAuthPoolCredentialUpdate {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetPool sets the "pool" edge to the OAuthPool entity.
func (_u *OAuthPoolCredentialUpdate) SetPool(v *OAuthPool) *OAuthPoolCredentialUpdate {
	return _u.SetPoolID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *OAuthPoolCredentialUpdate) SetAccount(v *Account) *OAuthPoolCredentialUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the OAuthPoolCredentialMutation object of the builder.
func (_u *OAuthPoolCredentialUpdate) Mutation() *OAuthPoolCredentialMutation {
	return _u.mutation
}

// ClearPool clears the "pool" edge to the OAuthPool entity.
func (_u *OAuthPoolCredentialUpdate) ClearPool() *OAuthPoolCredentialUpdate {
	_u.mutation.ClearPool()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *OAuthPoolCredentialUpdate) ClearAccount() *OAuthPoolCredentialUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthPoolCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthPoolCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthPoolCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthPoolCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthPoolCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthpoolcredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthPoolCredentialUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := oauthpoolcredential.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OAuthPoolCredential.state": %w`, err)}
		}
	}
	if _u.mutation.PoolCleared() && len(_u.mutation.PoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthPoolCredential.pool"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthPoolCredential.account"`)
	}
	return nil
}

func (_u *OAuthPoolCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthpoolcredential.Table, oauthpoolcredential.Columns, sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthpoolcredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(oauthpoolcredential.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(oauthpoolcredential.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(oauthpoolcredential.FieldCooldownUntil, field.TypeTime)
	}
	if _u.mutation.PoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpoolcredential.PoolTable,
			Columns: []string{oauthpoolcredential.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpoolcredential.PoolTable,
			Columns: []string{oauthpoolcredential.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   oauthpoolcredential.AccountTable,
			Columns: []string{oauthpoolcredential.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   oauthpoolcredential.AccountTable,
			Columns: []string{oauthpoolcredential.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthpoolcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthPoolCredentialUpdateOne is the builder for updating a single OAuthPoolCredential entity.
type OAuthPoolCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthPoolCredentialMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthPoolCredentialUpdateOne) SetUpdatedAt(v time.Time) *OAuthPoolCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPoolID sets the "pool_id" field.
func (_u *OAuthPoolCredentialUpdateOne) SetPoolID(v int64) *OAuthPoolCredentialUpdateOne {
	_u.mutation.SetPoolID(v)
	return _u
}

// SetNillablePoolID sets the "pool_id" field if the given value is not nil.
func (_u *OAuthPoolCredentialUpdateOne) SetNillablePoolID(v *int64) *OAuthPoolCredentialUpdateOne {
	if v != nil {
		_u.SetPoolID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OAuthPoolCredentialUpdateOne) SetAccountID(v int64) *OAuthPoolCredentialUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OAuthPoolCredentialUpdateOne) SetNillableAccountID(v *int64) *OAuthPoolCredentialUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *OAuthPoolCredentialUpdateOne) SetState(v string) *OAuthPoolCredentialUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *OAuthPoolCredentialUpdateOne) SetNillableState(v *string) *OAuthPoolCredentialUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *OAuthPoolCredentialUpdateOne) SetCooldownUntil(v time.Time) *OAuthPoolCredentialUpdateOne {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *OAuthPoolCredentialUpdateOne) SetNillableCooldownUntil(v *time.Time) *OAuthPoolCredentialUpdateOne {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *OAuthPoolCredentialUpdateOne) ClearCooldownUntil() *OAuthPoolCredentialUpdateOne {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetPool sets the "pool" edge to the OAuthPool entity.
func (_u *OAuthPoolCredentialUpdateOne) SetPool(v *OAuthPool) *OAuthPoolCredentialUpdateOne {
	return _u.SetPoolID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *OAuthPoolCredentialUpdateOne) SetAccount(v *Account) *OAuthPoolCredentialUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the OAuthPoolCredentialMutation object of the builder.
func (_u *OAuthPoolCredentialUpdateOne) Mutation() *OAuthPoolCredentialMutation {
	return _u.mutation
}

// ClearPool clears the "pool" edge to the OAuthPool entity.
func (_u *OAuthPoolCredentialUpdateOne) ClearPool() *OAuthPoolCredentialUpdateOne {
	_u.mutation.ClearPool()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *OAuthPoolCredentialUpdateOne) ClearAccount() *OAuthPoolCredentialUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the OAuthPoolCredentialUpdate builder.
func (_u *OAuthPoolCredentialUpdateOne) Where(ps ...predicate.OAuthPoolCredential) *OAuthPoolCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthPoolCredentialUpdateOne) Select(field string, fields ...string) *OAuthPoolCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthPoolCredential entity.
func (_u *OAuthPoolCredentialUpdateOne) Save(ctx context.Context) (*OAuthPoolCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthPoolCredentialUpdateOne) SaveX(ctx context.Context) *OAuthPoolCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthPoolCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthPoolCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthPoolCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthpoolcredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthPoolCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := oauthpoolcredential.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OAuthPoolCredential.state": %w`, err)}
		}
	}
	if _u.mutation.PoolCleared() && len(_u.mutation.PoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthPoolCredential.pool"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthPoolCredential.account"`)
	}
	return nil
}

func (_u *OAuthPoolCredentialUpdateOne) sqlSave(ctx context.Context) (_node *OAuthPoolCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthpoolcredential.Table, oauthpoolcredential.Columns, sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthPoolCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthpoolcredential.FieldID)
		for _, f := range fields {
			if !oauthpoolcredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthpoolcredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthpoolcredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(oauthpoolcredential.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(oauthpoolcredential.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(oauthpoolcredential.FieldCooldownUntil, field.TypeTime)
	}
	if _u.mutation.PoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpoolcredential.PoolTable,
			Columns: []string{oauthpoolcredential.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpoolcredential.PoolTable,
			Columns: []string{oauthpoolcredential.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   oauthpoolcredential.AccountTable,
			Columns: []string{oauthpoolcredential.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   oauthpoolcredential.AccountTable,
			Columns: []string{oauthpoolcredential.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthPoolCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthpoolcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
