// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dofastted/claude2api/ent/account"
	"github.com/dofastted/claude2api/ent/oauthpool"
	"github.com/dofastted/claude2api/ent/oauthpoolcredential"
)

// OAuthPoolCredentialCreate is the builder for creating a OAuthPoolCredential entity.
type OAuthPoolCredentialCreate struct {
	config
	mutation *OAuthPoolCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthPoolCredentialCreate) SetCreatedAt(v time.Time) *OAuthPoolCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthPoolCredentialCreate) SetNillableCreatedAt(v *time.Time) *OAuthPoolCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthPoolCredentialCreate) SetUpdatedAt(v time.Time) *OAuthPoolCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthPoolCredentialCreate) SetNillableUpdatedAt(v *time.Time) *OAuthPoolCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPoolID sets the "pool_id" field.
func (_c *OAuthPoolCredentialCreate) SetPoolID(v int64) *OAuthPoolCredentialCreate {
	_c.mutation.SetPoolID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *OAuthPoolCredentialCreate) SetAccountID(v int64) *OAuthPoolCredentialCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetState sets the "state" field.
func (_c *OAuthPoolCredentialCreate) SetState(v string) *OAuthPoolCredentialCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *OAuthPoolCredentialCreate) SetNillableState(v *string) *OAuthPoolCredentialCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_c *OAuthPoolCredentialCreate) SetCooldownUntil(v time.Time) *OAuthPoolCredentialCreate {
	_c.mutation.SetCooldownUntil(v)
	return _c
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_c *OAuthPoolCredentialCreate) SetNillableCooldownUntil(v *time.Time) *OAuthPoolCredentialCreate {
	if v != nil {
		_c.SetCooldownUntil(*v)
	}
	return _c
}

// SetPool sets the "pool" edge to the OAuthPool entity.
func (_c *OAuthPoolCredentialCreate) SetPool(v *OAuthPool) *OAuthPoolCredentialCreate {
	return _c.SetPoolID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *OAuthPoolCredentialCreate) SetAccount(v *Account) *OAuthPoolCredentialCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the OAuthPoolCredentialMutation object of the builder.
func (_c *OAuthPoolCredentialCreate) Mutation() *OAuthPoolCredentialMutation {
	return _c.mutation
}

// Save creates the OAuthPoolCredential in the database.
func (_c *OAuthPoolCredentialCreate) Save(ctx context.Context) (*OAuthPoolCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthPoolCredentialCreate) SaveX(ctx context.Context) *OAuthPoolCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthPoolCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthPoolCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthPoolCredentialCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthpoolcredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthpoolcredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := oauthpoolcredential.DefaultState
		_c.mutation.SetState(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthPoolCredentialCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthPoolCredential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthPoolCredential.updated_at"`)}
	}
	if _, ok := _c.mutation.PoolID(); !ok {
		return &ValidationError{Name: "pool_id", err: errors.New(`ent: missing required field "OAuthPoolCredential.pool_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OAuthPoolCredential.account_id"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "OAuthPoolCredential.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := oauthpoolcredential.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OAuthPoolCredential.state": %w`, err)}
		}
	}
	if len(_c.mutation.PoolIDs()) == 0 {
		return &ValidationError{Name: "pool", err: errors.New(`ent: missing required edge "OAuthPoolCredential.pool"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "OAuthPoolCredential.account"`)}
	}
	return nil
}

func (_c *OAuthPoolCredentialCreate) sqlSave(ctx context.Context) (*OAuthPoolCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthPoolCredentialCreate) createSpec() (*OAuthPoolCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthPoolCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthpoolcredential.Table, sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthpoolcredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthpoolcredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(oauthpoolcredential.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CooldownUntil(); ok {
		_spec.SetField(oauthpoolcredential.FieldCooldownUntil, field.TypeTime, value)
		_node.CooldownUntil = &value
	}
	if nodes := _c.mutation.PoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpoolcredential.PoolTable,
			Columns: []string{oauthpoolcredential.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PoolID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   oauthpoolcredential.AccountTable,
			Columns: []string{oauthpoolcredential.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthPoolCredential.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthPoolCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthPoolCredentialCreate) OnConflict(opts ...sql.ConflictOption) *OAuthPoolCredentialUpsertOne {
	_c.conflict = opts
	return &OAuthPoolCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthPoolCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthPoolCredentialCreate) OnConflictColumns(columns ...string) *OAuthPoolCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthPoolCredentialUpsertOne{
		create: _c,
	}
}

type (
	// OAuthPoolCredentialUpsertOne is the builder for "upsert"-ing
	//  one OAuthPoolCredential node.
	OAuthPoolCredentialUpsertOne struct {
		create *OAuthPoolCredentialCreate
	}

	// OAuthPoolCredentialUpsert is the "OnConflict" setter.
	OAuthPoolCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthPoolCredentialUpsert) SetUpdatedAt(v time.Time) *OAuthPoolCredentialUpsert {
	u.Set(oauthpoolcredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsert) UpdateUpdatedAt() *OAuthPoolCredentialUpsert {
	u.SetExcluded(oauthpoolcredential.FieldUpdatedAt)
	return u
}

// SetPoolID sets the "pool_id" field.
func (u *OAuthPoolCredentialUpsert) SetPoolID(v int64) *OAuthPoolCredentialUpsert {
	u.Set(oauthpoolcredential.FieldPoolID, v)
	return u
}

// UpdatePoolID sets the "pool_id" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsert) UpdatePoolID() *OAuthPoolCredentialUpsert {
	u.SetExcluded(oauthpoolcredential.FieldPoolID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OAuthPoolCredentialUpsert) SetAccountID(v int64) *OAuthPoolCredentialUpsert {
	u.Set(oauthpoolcredential.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsert) UpdateAccountID() *OAuthPoolCredentialUpsert {
	u.SetExcluded(oauthpoolcredential.FieldAccountID)
	return u
}

// SetState sets the "state" field.
func (u *OAuthPoolCredentialUpsert) SetState(v string) *OAuthPoolCredentialUpsert {
	u.Set(oauthpoolcredential.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsert) UpdateState() *OAuthPoolCredentialUpsert {
	u.SetExcluded(oauthpoolcredential.FieldState)
	return u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (u *OAuthPoolCredentialUpsert) SetCooldownUntil(v time.Time) *OAuthPoolCredentialUpsert {
	u.Set(oauthpoolcredential.FieldCooldownUntil, v)
	return u
}

// UpdateCooldownUntil sets the "cooldown_until" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsert) UpdateCooldownUntil() *OAuthPoolCredentialUpsert {
	u.SetExcluded(oauthpoolcredential.FieldCooldownUntil)
	return u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (u *OAuthPoolCredentialUpsert) ClearCooldownUntil() *OAuthPoolCredentialUpsert {
	u.SetNull(oauthpoolcredential.FieldCooldownUntil)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthPoolCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthPoolCredentialUpsertOne) UpdateNewValues() *OAuthPoolCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthpoolcredential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthPoolCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthPoolCredentialUpsertOne) Ignore() *OAuthPoolCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthPoolCredentialUpsertOne) DoNothing() *OAuthPoolCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthPoolCredentialCreate.OnConflict
// documentation for more info.
func (u *OAuthPoolCredentialUpsertOne) Update(set func(*OAuthPoolCredentialUpsert)) *OAuthPoolCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthPoolCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthPoolCredentialUpsertOne) SetUpdatedAt(v time.Time) *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertOne) UpdateUpdatedAt() *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPoolID sets the "pool_id" field.
func (u *OAuthPoolCredentialUpsertOne) SetPoolID(v int64) *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetPoolID(v)
	})
}

// UpdatePoolID sets the "pool_id" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertOne) UpdatePoolID() *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdatePoolID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OAuthPoolCredentialUpsertOne) SetAccountID(v int64) *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertOne) UpdateAccountID() *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdateAccountID()
	})
}

// SetState sets the "state" field.
func (u *OAuthPoolCredentialUpsertOne) SetState(v string) *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertOne) UpdateState() *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdateState()
	})
}

// SetCooldownUntil sets the "cooldown_until" field.
func (u *OAuthPoolCredentialUpsertOne) SetCooldownUntil(v time.Time) *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetCooldownUntil(v)
	})
}

// UpdateCooldownUntil sets the "cooldown_until" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertOne) UpdateCooldownUntil() *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdateCooldownUntil()
	})
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (u *OAuthPoolCredentialUpsertOne) ClearCooldownUntil() *OAuthPoolCredentialUpsertOne {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.ClearCooldownUntil()
	})
}

// Exec executes the query.
func (u *OAuthPoolCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthPoolCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthPoolCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthPoolCredentialUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthPoolCredentialUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthPoolCredentialCreateBulk is the builder for creating many OAuthPoolCredential entities in bulk.
type OAuthPoolCredentialCreateBulk struct {
	config
	err      error
	builders []*OAuthPoolCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthPoolCredential entities in the database.
func (_c *OAuthPoolCredentialCreateBulk) Save(ctx context.Context) ([]*OAuthPoolCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthPoolCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthPoolCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthPoolCredentialCreateBulk) SaveX(ctx context.Context) []*OAuthPoolCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthPoolCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthPoolCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthPoolCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthPoolCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthPoolCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthPoolCredentialUpsertBulk {
	_c.conflict = opts
	return &OAuthPoolCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthPoolCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthPoolCredentialCreateBulk) OnConflictColumns(columns ...string) *OAuthPoolCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthPoolCredentialUpsertBulk{
		create: _c,
	}
}

// OAuthPoolCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthPoolCredential nodes.
type OAuthPoolCredentialUpsertBulk struct {
	create *OAuthPoolCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthPoolCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthPoolCredentialUpsertBulk) UpdateNewValues() *OAuthPoolCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthpoolcredential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthPoolCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthPoolCredentialUpsertBulk) Ignore() *OAuthPoolCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthPoolCredentialUpsertBulk) DoNothing() *OAuthPoolCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthPoolCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthPoolCredentialUpsertBulk) Update(set func(*OAuthPoolCredentialUpsert)) *OAuthPoolCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthPoolCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthPoolCredentialUpsertBulk) SetUpdatedAt(v time.Time) *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertBulk) UpdateUpdatedAt() *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPoolID sets the "pool_id" field.
func (u *OAuthPoolCredentialUpsertBulk) SetPoolID(v int64) *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetPoolID(v)
	})
}

// UpdatePoolID sets the "pool_id" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertBulk) UpdatePoolID() *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdatePoolID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OAuthPoolCredentialUpsertBulk) SetAccountID(v int64) *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertBulk) UpdateAccountID() *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdateAccountID()
	})
}

// SetState sets the "state" field.
func (u *OAuthPoolCredentialUpsertBulk) SetState(v string) *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertBulk) UpdateState() *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdateState()
	})
}

// SetCooldownUntil sets the "cooldown_until" field.
func (u *OAuthPoolCredentialUpsertBulk) SetCooldownUntil(v time.Time) *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.SetCooldownUntil(v)
	})
}

// UpdateCooldownUntil sets the "cooldown_until" field to the value that was provided on create.
func (u *OAuthPoolCredentialUpsertBulk) UpdateCooldownUntil() *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.UpdateCooldownUntil()
	})
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (u *OAuthPoolCredentialUpsertBulk) ClearCooldownUntil() *OAuthPoolCredentialUpsertBulk {
	return u.Update(func(s *OAuthPoolCredentialUpsert) {
		s.ClearCooldownUntil()
	})
}

// Exec executes the query.
func (u *OAuthPoolCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthPoolCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthPoolCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthPoolCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
