// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dofastted/claude2api/ent/oauthcapsuleset"
	"github.com/dofastted/claude2api/ent/oauthpool"
	"github.com/dofastted/claude2api/ent/predicate"
)

// OAuthCapsuleSetUpdate is the builder for updating OAuthCapsuleSet entities.
type OAuthCapsuleSetUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthCapsuleSetMutation
}

// Where appends a list predicates to the OAuthCapsuleSetUpdate builder.
func (_u *OAuthCapsuleSetUpdate) Where(ps ...predicate.OAuthCapsuleSet) *OAuthCapsuleSetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthCapsuleSetUpdate) SetUpdatedAt(v time.Time) *OAuthCapsuleSetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPoolID sets the "pool_id" field.
func (_u *OAuthCapsuleSetUpdate) SetPoolID(v int64) *OAuthCapsuleSetUpdate {
	_u.mutation.SetPoolID(v)
	return _u
}

// SetNillablePoolID sets the "pool_id" field if the given value is not nil.
func (_u *OAuthCapsuleSetUpdate) SetNillablePoolID(v *int64) *OAuthCapsuleSetUpdate {
	if v != nil {
		_u.SetPoolID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *OAuthCapsuleSetUpdate) SetVersion(v int64) *OAuthCapsuleSetUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OAuthCapsuleSetUpdate) SetNillableVersion(v *int64) *OAuthCapsuleSetUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *OAuthCapsuleSetUpdate) AddVersion(v int64) *OAuthCapsuleSetUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (_u *OAuthCapsuleSetUpdate) SetCompatibilityDigest(v string) *OAuthCapsuleSetUpdate {
	_u.mutation.SetCompatibilityDigest(v)
	return _u
}

// SetNillableCompatibilityDigest sets the "compatibility_digest" field if the given value is not nil.
func (_u *OAuthCapsuleSetUpdate) SetNillableCompatibilityDigest(v *string) *OAuthCapsuleSetUpdate {
	if v != nil {
		_u.SetCompatibilityDigest(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OAuthCapsuleSetUpdate) SetPayload(v map[string]interface{}) *OAuthCapsuleSetUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetPool sets the "pool" edge to the OAuthPool entity.
func (_u *OAuthCapsuleSetUpdate) SetPool(v *OAuthPool) *OAuthCapsuleSetUpdate {
	return _u.SetPoolID(v.ID)
}

// Mutation returns the OAuthCapsuleSetMutation object of the builder.
func (_u *OAuthCapsuleSetUpdate) Mutation() *OAuthCapsuleSetMutation {
	return _u.mutation
}

// ClearPool clears the "pool" edge to the OAuthPool entity.
func (_u *OAuthCapsuleSetUpdate) ClearPool() *OAuthCapsuleSetUpdate {
	_u.mutation.ClearPool()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthCapsuleSetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthCapsuleSetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthCapsuleSetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthCapsuleSetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthCapsuleSetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthcapsuleset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthCapsuleSetUpdate) check() error {
	if v, ok := _u.mutation.CompatibilityDigest(); ok {
		if err := oauthcapsuleset.CompatibilityDigestValidator(v); err != nil {
			return &ValidationError{Name: "compatibility_digest", err: fmt.Errorf(`ent: validator failed for field "OAuthCapsuleSet.compatibility_digest": %w`, err)}
		}
	}
	if _u.mutation.PoolCleared() && len(_u.mutation.PoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthCapsuleSet.pool"`)
	}
	return nil
}

func (_u *OAuthCapsuleSetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthcapsuleset.Table, oauthcapsuleset.Columns, sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthcapsuleset.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(oauthcapsuleset.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(oauthcapsuleset.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompatibilityDigest(); ok {
		_spec.SetField(oauthcapsuleset.FieldCompatibilityDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(oauthcapsuleset.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthcapsuleset.PoolTable,
			Columns: []string{oauthcapsuleset.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthcapsuleset.PoolTable,
			Columns: []string{oauthcapsuleset.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthcapsuleset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthCapsuleSetUpdateOne is the builder for updating a single OAuthCapsuleSet entity.
type OAuthCapsuleSetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthCapsuleSetMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthCapsuleSetUpdateOne) SetUpdatedAt(v time.Time) *OAuthCapsuleSetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPoolID sets the "pool_id" field.
func (_u *OAuthCapsuleSetUpdateOne) SetPoolID(v int64) *OAuthCapsuleSetUpdateOne {
	_u.mutation.SetPoolID(v)
	return _u
}

// SetNillablePoolID sets the "pool_id" field if the given value is not nil.
func (_u *OAuthCapsuleSetUpdateOne) SetNillablePoolID(v *int64) *OAuthCapsuleSetUpdateOne {
	if v != nil {
		_u.SetPoolID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *OAuthCapsuleSetUpdateOne) SetVersion(v int64) *OAuthCapsuleSetUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OAuthCapsuleSetUpdateOne) SetNillableVersion(v *int64) *OAuthCapsuleSetUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *OAuthCapsuleSetUpdateOne) AddVersion(v int64) *OAuthCapsuleSetUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (_u *OAuthCapsuleSetUpdateOne) SetCompatibilityDigest(v string) *OAuthCapsuleSetUpdateOne {
	_u.mutation.SetCompatibilityDigest(v)
	return _u
}

// SetNillableCompatibilityDigest sets the "compatibility_digest" field if the given value is not nil.
func (_u *OAuthCapsuleSetUpdateOne) SetNillableCompatibilityDigest(v *string) *OAuthCapsuleSetUpdateOne {
	if v != nil {
		_u.SetCompatibilityDigest(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OAuthCapsuleSetUpdateOne) SetPayload(v map[string]interface{}) *OAuthCapsuleSetUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetPool sets the "pool" edge to the OAuthPool entity.
func (_u *OAuthCapsuleSetUpdateOne) SetPool(v *OAuthPool) *OAuthCapsuleSetUpdateOne {
	return _u.SetPoolID(v.ID)
}

// Mutation returns the OAuthCapsuleSetMutation object of the builder.
func (_u *OAuthCapsuleSetUpdateOne) Mutation() *OAuthCapsuleSetMutation {
	return _u.mutation
}

// ClearPool clears the "pool" edge to the OAuthPool entity.
func (_u *OAuthCapsuleSetUpdateOne) ClearPool() *OAuthCapsuleSetUpdateOne {
	_u.mutation.ClearPool()
	return _u
}

// Where appends a list predicates to the OAuthCapsuleSetUpdate builder.
func (_u *OAuthCapsuleSetUpdateOne) Where(ps ...predicate.OAuthCapsuleSet) *OAuthCapsuleSetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthCapsuleSetUpdateOne) Select(field string, fields ...string) *OAuthCapsuleSetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthCapsuleSet entity.
func (_u *OAuthCapsuleSetUpdateOne) Save(ctx context.Context) (*OAuthCapsuleSet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthCapsuleSetUpdateOne) SaveX(ctx context.Context) *OAuthCapsuleSet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthCapsuleSetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthCapsuleSetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthCapsuleSetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthcapsuleset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthCapsuleSetUpdateOne) check() error {
	if v, ok := _u.mutation.CompatibilityDigest(); ok {
		if err := oauthcapsuleset.CompatibilityDigestValidator(v); err != nil {
			return &ValidationError{Name: "compatibility_digest", err: fmt.Errorf(`ent: validator failed for field "OAuthCapsuleSet.compatibility_digest": %w`, err)}
		}
	}
	if _u.mutation.PoolCleared() && len(_u.mutation.PoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthCapsuleSet.pool"`)
	}
	return nil
}

func (_u *OAuthCapsuleSetUpdateOne) sqlSave(ctx context.Context) (_node *OAuthCapsuleSet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthcapsuleset.Table, oauthcapsuleset.Columns, sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthCapsuleSet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthcapsuleset.FieldID)
		for _, f := range fields {
			if !oauthcapsuleset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthcapsuleset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthcapsuleset.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(oauthcapsuleset.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(oauthcapsuleset.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CompatibilityDigest(); ok {
		_spec.SetField(oauthcapsuleset.FieldCompatibilityDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(oauthcapsuleset.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthcapsuleset.PoolTable,
			Columns: []string{oauthcapsuleset.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthcapsuleset.PoolTable,
			Columns: []string{oauthcapsuleset.PoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthCapsuleSet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthcapsuleset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
