// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dofastted/claude2api/ent/group"
	"github.com/dofastted/claude2api/ent/oauthcapsuleset"
	"github.com/dofastted/claude2api/ent/oauthpool"
	"github.com/dofastted/claude2api/ent/oauthpoolcredential"
	"github.com/dofastted/claude2api/ent/proxy"
)

// OAuthPoolCreate is the builder for creating a OAuthPool entity.
type OAuthPoolCreate struct {
	config
	mutation *OAuthPoolMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthPoolCreate) SetCreatedAt(v time.Time) *OAuthPoolCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableCreatedAt(v *time.Time) *OAuthPoolCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthPoolCreate) SetUpdatedAt(v time.Time) *OAuthPoolCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableUpdatedAt(v *time.Time) *OAuthPoolCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OAuthPoolCreate) SetDeletedAt(v time.Time) *OAuthPoolCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableDeletedAt(v *time.Time) *OAuthPoolCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *OAuthPoolCreate) SetName(v string) *OAuthPoolCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *OAuthPoolCreate) SetProvider(v string) *OAuthPoolCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableProvider(v *string) *OAuthPoolCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OAuthPoolCreate) SetStatus(v string) *OAuthPoolCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableStatus(v *string) *OAuthPoolCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *OAuthPoolCreate) SetMode(v string) *OAuthPoolCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableMode(v *string) *OAuthPoolCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetEgressRouteID sets the "egress_route_id" field.
func (_c *OAuthPoolCreate) SetEgressRouteID(v int64) *OAuthPoolCreate {
	_c.mutation.SetEgressRouteID(v)
	return _c
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (_c *OAuthPoolCreate) SetAllowedOrigins(v []string) *OAuthPoolCreate {
	_c.mutation.SetAllowedOrigins(v)
	return _c
}

// SetAllowedModels sets the "allowed_models" field.
func (_c *OAuthPoolCreate) SetAllowedModels(v []string) *OAuthPoolCreate {
	_c.mutation.SetAllowedModels(v)
	return _c
}

// SetActiveCapsuleSetVersion sets the "active_capsule_set_version" field.
func (_c *OAuthPoolCreate) SetActiveCapsuleSetVersion(v int64) *OAuthPoolCreate {
	_c.mutation.SetActiveCapsuleSetVersion(v)
	return _c
}

// SetNillableActiveCapsuleSetVersion sets the "active_capsule_set_version" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableActiveCapsuleSetVersion(v *int64) *OAuthPoolCreate {
	if v != nil {
		_c.SetActiveCapsuleSetVersion(*v)
	}
	return _c
}

// SetPreviousCapsuleSetVersion sets the "previous_capsule_set_version" field.
func (_c *OAuthPoolCreate) SetPreviousCapsuleSetVersion(v int64) *OAuthPoolCreate {
	_c.mutation.SetPreviousCapsuleSetVersion(v)
	return _c
}

// SetNillablePreviousCapsuleSetVersion sets the "previous_capsule_set_version" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillablePreviousCapsuleSetVersion(v *int64) *OAuthPoolCreate {
	if v != nil {
		_c.SetPreviousCapsuleSetVersion(*v)
	}
	return _c
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (_c *OAuthPoolCreate) SetCompatibilityDigest(v string) *OAuthPoolCreate {
	_c.mutation.SetCompatibilityDigest(v)
	return _c
}

// SetNillableCompatibilityDigest sets the "compatibility_digest" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableCompatibilityDigest(v *string) *OAuthPoolCreate {
	if v != nil {
		_c.SetCompatibilityDigest(*v)
	}
	return _c
}

// SetSessionTTLSeconds sets the "session_ttl_seconds" field.
func (_c *OAuthPoolCreate) SetSessionTTLSeconds(v int) *OAuthPoolCreate {
	_c.mutation.SetSessionTTLSeconds(v)
	return _c
}

// SetNillableSessionTTLSeconds sets the "session_ttl_seconds" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableSessionTTLSeconds(v *int) *OAuthPoolCreate {
	if v != nil {
		_c.SetSessionTTLSeconds(*v)
	}
	return _c
}

// SetShadowStartedAt sets the "shadow_started_at" field.
func (_c *OAuthPoolCreate) SetShadowStartedAt(v time.Time) *OAuthPoolCreate {
	_c.mutation.SetShadowStartedAt(v)
	return _c
}

// SetNillableShadowStartedAt sets the "shadow_started_at" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableShadowStartedAt(v *time.Time) *OAuthPoolCreate {
	if v != nil {
		_c.SetShadowStartedAt(*v)
	}
	return _c
}

// SetShadowQualifiedAt sets the "shadow_qualified_at" field.
func (_c *OAuthPoolCreate) SetShadowQualifiedAt(v time.Time) *OAuthPoolCreate {
	_c.mutation.SetShadowQualifiedAt(v)
	return _c
}

// SetNillableShadowQualifiedAt sets the "shadow_qualified_at" field if the given value is not nil.
func (_c *OAuthPoolCreate) SetNillableShadowQualifiedAt(v *time.Time) *OAuthPoolCreate {
	if v != nil {
		_c.SetShadowQualifiedAt(*v)
	}
	return _c
}

// SetEgressRoute sets the "egress_route" edge to the Proxy entity.
func (_c *OAuthPoolCreate) SetEgressRoute(v *Proxy) *OAuthPoolCreate {
	return _c.SetEgressRouteID(v.ID)
}

// AddCredentialIDs adds the "credentials" edge to the OAuthPoolCredential entity by IDs.
func (_c *OAuthPoolCreate) AddCredentialIDs(ids ...int64) *OAuthPoolCreate {
	_c.mutation.AddCredentialIDs(ids...)
	return _c
}

// AddCredentials adds the "credentials" edges to the OAuthPoolCredential entity.
func (_c *OAuthPoolCreate) AddCredentials(v ...*OAuthPoolCredential) *OAuthPoolCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCredentialIDs(ids...)
}

// AddCapsuleSetIDs adds the "capsule_sets" edge to the OAuthCapsuleSet entity by IDs.
func (_c *OAuthPoolCreate) AddCapsuleSetIDs(ids ...int64) *OAuthPoolCreate {
	_c.mutation.AddCapsuleSetIDs(ids...)
	return _c
}

// AddCapsuleSets adds the "capsule_sets" edges to the OAuthCapsuleSet entity.
func (_c *OAuthPoolCreate) AddCapsuleSets(v ...*OAuthCapsuleSet) *OAuthPoolCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCapsuleSetIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_c *OAuthPoolCreate) AddGroupIDs(ids ...int64) *OAuthPoolCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the Group entity.
func (_c *OAuthPoolCreate) AddGroups(v ...*Group) *OAuthPoolCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// Mutation returns the OAuthPoolMutation object of the builder.
func (_c *OAuthPoolCreate) Mutation() *OAuthPoolMutation {
	return _c.mutation
}

// Save creates the OAuthPool in the database.
func (_c *OAuthPoolCreate) Save(ctx context.Context) (*OAuthPool, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthPoolCreate) SaveX(ctx context.Context) *OAuthPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthPoolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthPoolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthPoolCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if oauthpool.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized oauthpool.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := oauthpool.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if oauthpool.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized oauthpool.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := oauthpool.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := oauthpool.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := oauthpool.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := oauthpool.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.AllowedOrigins(); !ok {
		v := oauthpool.DefaultAllowedOrigins
		_c.mutation.SetAllowedOrigins(v)
	}
	if _, ok := _c.mutation.AllowedModels(); !ok {
		v := oauthpool.DefaultAllowedModels
		_c.mutation.SetAllowedModels(v)
	}
	if _, ok := _c.mutation.ActiveCapsuleSetVersion(); !ok {
		v := oauthpool.DefaultActiveCapsuleSetVersion
		_c.mutation.SetActiveCapsuleSetVersion(v)
	}
	if _, ok := _c.mutation.CompatibilityDigest(); !ok {
		v := oauthpool.DefaultCompatibilityDigest
		_c.mutation.SetCompatibilityDigest(v)
	}
	if _, ok := _c.mutation.SessionTTLSeconds(); !ok {
		v := oauthpool.DefaultSessionTTLSeconds
		_c.mutation.SetSessionTTLSeconds(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthPoolCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthPool.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthPool.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OAuthPool.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oauthpool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "OAuthPool.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := oauthpool.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OAuthPool.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := oauthpool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "OAuthPool.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := oauthpool.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EgressRouteID(); !ok {
		return &ValidationError{Name: "egress_route_id", err: errors.New(`ent: missing required field "OAuthPool.egress_route_id"`)}
	}
	if _, ok := _c.mutation.AllowedOrigins(); !ok {
		return &ValidationError{Name: "allowed_origins", err: errors.New(`ent: missing required field "OAuthPool.allowed_origins"`)}
	}
	if _, ok := _c.mutation.AllowedModels(); !ok {
		return &ValidationError{Name: "allowed_models", err: errors.New(`ent: missing required field "OAuthPool.allowed_models"`)}
	}
	if _, ok := _c.mutation.ActiveCapsuleSetVersion(); !ok {
		return &ValidationError{Name: "active_capsule_set_version", err: errors.New(`ent: missing required field "OAuthPool.active_capsule_set_version"`)}
	}
	if _, ok := _c.mutation.CompatibilityDigest(); !ok {
		return &ValidationError{Name: "compatibility_digest", err: errors.New(`ent: missing required field "OAuthPool.compatibility_digest"`)}
	}
	if v, ok := _c.mutation.CompatibilityDigest(); ok {
		if err := oauthpool.CompatibilityDigestValidator(v); err != nil {
			return &ValidationError{Name: "compatibility_digest", err: fmt.Errorf(`ent: validator failed for field "OAuthPool.compatibility_digest": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionTTLSeconds(); !ok {
		return &ValidationError{Name: "session_ttl_seconds", err: errors.New(`ent: missing required field "OAuthPool.session_ttl_seconds"`)}
	}
	if len(_c.mutation.EgressRouteIDs()) == 0 {
		return &ValidationError{Name: "egress_route", err: errors.New(`ent: missing required edge "OAuthPool.egress_route"`)}
	}
	return nil
}

func (_c *OAuthPoolCreate) sqlSave(ctx context.Context) (*OAuthPool, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthPoolCreate) createSpec() (*OAuthPool, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthPool{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthpool.Table, sqlgraph.NewFieldSpec(oauthpool.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthpool.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthpool.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(oauthpool.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauthpool.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(oauthpool.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(oauthpool.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(oauthpool.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.AllowedOrigins(); ok {
		_spec.SetField(oauthpool.FieldAllowedOrigins, field.TypeJSON, value)
		_node.AllowedOrigins = value
	}
	if value, ok := _c.mutation.AllowedModels(); ok {
		_spec.SetField(oauthpool.FieldAllowedModels, field.TypeJSON, value)
		_node.AllowedModels = value
	}
	if value, ok := _c.mutation.ActiveCapsuleSetVersion(); ok {
		_spec.SetField(oauthpool.FieldActiveCapsuleSetVersion, field.TypeInt64, value)
		_node.ActiveCapsuleSetVersion = value
	}
	if value, ok := _c.mutation.PreviousCapsuleSetVersion(); ok {
		_spec.SetField(oauthpool.FieldPreviousCapsuleSetVersion, field.TypeInt64, value)
		_node.PreviousCapsuleSetVersion = &value
	}
	if value, ok := _c.mutation.CompatibilityDigest(); ok {
		_spec.SetField(oauthpool.FieldCompatibilityDigest, field.TypeString, value)
		_node.CompatibilityDigest = value
	}
	if value, ok := _c.mutation.SessionTTLSeconds(); ok {
		_spec.SetField(oauthpool.FieldSessionTTLSeconds, field.TypeInt, value)
		_node.SessionTTLSeconds = value
	}
	if value, ok := _c.mutation.ShadowStartedAt(); ok {
		_spec.SetField(oauthpool.FieldShadowStartedAt, field.TypeTime, value)
		_node.ShadowStartedAt = &value
	}
	if value, ok := _c.mutation.ShadowQualifiedAt(); ok {
		_spec.SetField(oauthpool.FieldShadowQualifiedAt, field.TypeTime, value)
		_node.ShadowQualifiedAt = &value
	}
	if nodes := _c.mutation.EgressRouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthpool.EgressRouteTable,
			Columns: []string{oauthpool.EgressRouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EgressRouteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CredentialsTable,
			Columns: []string{oauthpool.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthpoolcredential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CapsuleSetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.CapsuleSetsTable,
			Columns: []string{oauthpool.CapsuleSetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthcapsuleset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthpool.GroupsTable,
			Columns: []string{oauthpool.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthPool.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthPoolCreate) OnConflict(opts ...sql.ConflictOption) *OAuthPoolUpsertOne {
	_c.conflict = opts
	return &OAuthPoolUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthPoolCreate) OnConflictColumns(columns ...string) *OAuthPoolUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthPoolUpsertOne{
		create: _c,
	}
}

type (
	// OAuthPoolUpsertOne is the builder for "upsert"-ing
	//  one OAuthPool node.
	OAuthPoolUpsertOne struct {
		create *OAuthPoolCreate
	}

	// OAuthPoolUpsert is the "OnConflict" setter.
	OAuthPoolUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthPoolUpsert) SetUpdatedAt(v time.Time) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateUpdatedAt() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OAuthPoolUpsert) SetDeletedAt(v time.Time) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateDeletedAt() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OAuthPoolUpsert) ClearDeletedAt() *OAuthPoolUpsert {
	u.SetNull(oauthpool.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *OAuthPoolUpsert) SetName(v string) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateName() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldName)
	return u
}

// SetProvider sets the "provider" field.
func (u *OAuthPoolUpsert) SetProvider(v string) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateProvider() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldProvider)
	return u
}

// SetStatus sets the "status" field.
func (u *OAuthPoolUpsert) SetStatus(v string) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateStatus() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldStatus)
	return u
}

// SetMode sets the "mode" field.
func (u *OAuthPoolUpsert) SetMode(v string) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateMode() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldMode)
	return u
}

// SetEgressRouteID sets the "egress_route_id" field.
func (u *OAuthPoolUpsert) SetEgressRouteID(v int64) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldEgressRouteID, v)
	return u
}

// UpdateEgressRouteID sets the "egress_route_id" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateEgressRouteID() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldEgressRouteID)
	return u
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (u *OAuthPoolUpsert) SetAllowedOrigins(v []string) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldAllowedOrigins, v)
	return u
}

// UpdateAllowedOrigins sets the "allowed_origins" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateAllowedOrigins() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldAllowedOrigins)
	return u
}

// SetAllowedModels sets the "allowed_models" field.
func (u *OAuthPoolUpsert) SetAllowedModels(v []string) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldAllowedModels, v)
	return u
}

// UpdateAllowedModels sets the "allowed_models" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateAllowedModels() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldAllowedModels)
	return u
}

// SetActiveCapsuleSetVersion sets the "active_capsule_set_version" field.
func (u *OAuthPoolUpsert) SetActiveCapsuleSetVersion(v int64) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldActiveCapsuleSetVersion, v)
	return u
}

// UpdateActiveCapsuleSetVersion sets the "active_capsule_set_version" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateActiveCapsuleSetVersion() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldActiveCapsuleSetVersion)
	return u
}

// AddActiveCapsuleSetVersion adds v to the "active_capsule_set_version" field.
func (u *OAuthPoolUpsert) AddActiveCapsuleSetVersion(v int64) *OAuthPoolUpsert {
	u.Add(oauthpool.FieldActiveCapsuleSetVersion, v)
	return u
}

// SetPreviousCapsuleSetVersion sets the "previous_capsule_set_version" field.
func (u *OAuthPoolUpsert) SetPreviousCapsuleSetVersion(v int64) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldPreviousCapsuleSetVersion, v)
	return u
}

// UpdatePreviousCapsuleSetVersion sets the "previous_capsule_set_version" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdatePreviousCapsuleSetVersion() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldPreviousCapsuleSetVersion)
	return u
}

// AddPreviousCapsuleSetVersion adds v to the "previous_capsule_set_version" field.
func (u *OAuthPoolUpsert) AddPreviousCapsuleSetVersion(v int64) *OAuthPoolUpsert {
	u.Add(oauthpool.FieldPreviousCapsuleSetVersion, v)
	return u
}

// ClearPreviousCapsuleSetVersion clears the value of the "previous_capsule_set_version" field.
func (u *OAuthPoolUpsert) ClearPreviousCapsuleSetVersion() *OAuthPoolUpsert {
	u.SetNull(oauthpool.FieldPreviousCapsuleSetVersion)
	return u
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (u *OAuthPoolUpsert) SetCompatibilityDigest(v string) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldCompatibilityDigest, v)
	return u
}

// UpdateCompatibilityDigest sets the "compatibility_digest" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateCompatibilityDigest() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldCompatibilityDigest)
	return u
}

// SetSessionTTLSeconds sets the "session_ttl_seconds" field.
func (u *OAuthPoolUpsert) SetSessionTTLSeconds(v int) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldSessionTTLSeconds, v)
	return u
}

// UpdateSessionTTLSeconds sets the "session_ttl_seconds" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateSessionTTLSeconds() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldSessionTTLSeconds)
	return u
}

// AddSessionTTLSeconds adds v to the "session_ttl_seconds" field.
func (u *OAuthPoolUpsert) AddSessionTTLSeconds(v int) *OAuthPoolUpsert {
	u.Add(oauthpool.FieldSessionTTLSeconds, v)
	return u
}

// SetShadowStartedAt sets the "shadow_started_at" field.
func (u *OAuthPoolUpsert) SetShadowStartedAt(v time.Time) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldShadowStartedAt, v)
	return u
}

// UpdateShadowStartedAt sets the "shadow_started_at" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateShadowStartedAt() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldShadowStartedAt)
	return u
}

// ClearShadowStartedAt clears the value of the "shadow_started_at" field.
func (u *OAuthPoolUpsert) ClearShadowStartedAt() *OAuthPoolUpsert {
	u.SetNull(oauthpool.FieldShadowStartedAt)
	return u
}

// SetShadowQualifiedAt sets the "shadow_qualified_at" field.
func (u *OAuthPoolUpsert) SetShadowQualifiedAt(v time.Time) *OAuthPoolUpsert {
	u.Set(oauthpool.FieldShadowQualifiedAt, v)
	return u
}

// UpdateShadowQualifiedAt sets the "shadow_qualified_at" field to the value that was provided on create.
func (u *OAuthPoolUpsert) UpdateShadowQualifiedAt() *OAuthPoolUpsert {
	u.SetExcluded(oauthpool.FieldShadowQualifiedAt)
	return u
}

// ClearShadowQualifiedAt clears the value of the "shadow_qualified_at" field.
func (u *OAuthPoolUpsert) ClearShadowQualifiedAt() *OAuthPoolUpsert {
	u.SetNull(oauthpool.FieldShadowQualifiedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthPoolUpsertOne) UpdateNewValues() *OAuthPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthpool.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthPool.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthPoolUpsertOne) Ignore() *OAuthPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthPoolUpsertOne) DoNothing() *OAuthPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthPoolCreate.OnConflict
// documentation for more info.
func (u *OAuthPoolUpsertOne) Update(set func(*OAuthPoolUpsert)) *OAuthPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthPoolUpsertOne) SetUpdatedAt(v time.Time) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateUpdatedAt() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OAuthPoolUpsertOne) SetDeletedAt(v time.Time) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateDeletedAt() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OAuthPoolUpsertOne) ClearDeletedAt() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *OAuthPoolUpsertOne) SetName(v string) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateName() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateName()
	})
}

// SetProvider sets the "provider" field.
func (u *OAuthPoolUpsertOne) SetProvider(v string) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateProvider() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateProvider()
	})
}

// SetStatus sets the "status" field.
func (u *OAuthPoolUpsertOne) SetStatus(v string) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateStatus() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateStatus()
	})
}

// SetMode sets the "mode" field.
func (u *OAuthPoolUpsertOne) SetMode(v string) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateMode() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateMode()
	})
}

// SetEgressRouteID sets the "egress_route_id" field.
func (u *OAuthPoolUpsertOne) SetEgressRouteID(v int64) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetEgressRouteID(v)
	})
}

// UpdateEgressRouteID sets the "egress_route_id" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateEgressRouteID() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateEgressRouteID()
	})
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (u *OAuthPoolUpsertOne) SetAllowedOrigins(v []string) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetAllowedOrigins(v)
	})
}

// UpdateAllowedOrigins sets the "allowed_origins" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateAllowedOrigins() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateAllowedOrigins()
	})
}

// SetAllowedModels sets the "allowed_models" field.
func (u *OAuthPoolUpsertOne) SetAllowedModels(v []string) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetAllowedModels(v)
	})
}

// UpdateAllowedModels sets the "allowed_models" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateAllowedModels() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateAllowedModels()
	})
}

// SetActiveCapsuleSetVersion sets the "active_capsule_set_version" field.
func (u *OAuthPoolUpsertOne) SetActiveCapsuleSetVersion(v int64) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetActiveCapsuleSetVersion(v)
	})
}

// AddActiveCapsuleSetVersion adds v to the "active_capsule_set_version" field.
func (u *OAuthPoolUpsertOne) AddActiveCapsuleSetVersion(v int64) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.AddActiveCapsuleSetVersion(v)
	})
}

// UpdateActiveCapsuleSetVersion sets the "active_capsule_set_version" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateActiveCapsuleSetVersion() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateActiveCapsuleSetVersion()
	})
}

// SetPreviousCapsuleSetVersion sets the "previous_capsule_set_version" field.
func (u *OAuthPoolUpsertOne) SetPreviousCapsuleSetVersion(v int64) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetPreviousCapsuleSetVersion(v)
	})
}

// AddPreviousCapsuleSetVersion adds v to the "previous_capsule_set_version" field.
func (u *OAuthPoolUpsertOne) AddPreviousCapsuleSetVersion(v int64) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.AddPreviousCapsuleSetVersion(v)
	})
}

// UpdatePreviousCapsuleSetVersion sets the "previous_capsule_set_version" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdatePreviousCapsuleSetVersion() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdatePreviousCapsuleSetVersion()
	})
}

// ClearPreviousCapsuleSetVersion clears the value of the "previous_capsule_set_version" field.
func (u *OAuthPoolUpsertOne) ClearPreviousCapsuleSetVersion() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.ClearPreviousCapsuleSetVersion()
	})
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (u *OAuthPoolUpsertOne) SetCompatibilityDigest(v string) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetCompatibilityDigest(v)
	})
}

// UpdateCompatibilityDigest sets the "compatibility_digest" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateCompatibilityDigest() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateCompatibilityDigest()
	})
}

// SetSessionTTLSeconds sets the "session_ttl_seconds" field.
func (u *OAuthPoolUpsertOne) SetSessionTTLSeconds(v int) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetSessionTTLSeconds(v)
	})
}

// AddSessionTTLSeconds adds v to the "session_ttl_seconds" field.
func (u *OAuthPoolUpsertOne) AddSessionTTLSeconds(v int) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.AddSessionTTLSeconds(v)
	})
}

// UpdateSessionTTLSeconds sets the "session_ttl_seconds" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateSessionTTLSeconds() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateSessionTTLSeconds()
	})
}

// SetShadowStartedAt sets the "shadow_started_at" field.
func (u *OAuthPoolUpsertOne) SetShadowStartedAt(v time.Time) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetShadowStartedAt(v)
	})
}

// UpdateShadowStartedAt sets the "shadow_started_at" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateShadowStartedAt() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateShadowStartedAt()
	})
}

// ClearShadowStartedAt clears the value of the "shadow_started_at" field.
func (u *OAuthPoolUpsertOne) ClearShadowStartedAt() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.ClearShadowStartedAt()
	})
}

// SetShadowQualifiedAt sets the "shadow_qualified_at" field.
func (u *OAuthPoolUpsertOne) SetShadowQualifiedAt(v time.Time) *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetShadowQualifiedAt(v)
	})
}

// UpdateShadowQualifiedAt sets the "shadow_qualified_at" field to the value that was provided on create.
func (u *OAuthPoolUpsertOne) UpdateShadowQualifiedAt() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateShadowQualifiedAt()
	})
}

// ClearShadowQualifiedAt clears the value of the "shadow_qualified_at" field.
func (u *OAuthPoolUpsertOne) ClearShadowQualifiedAt() *OAuthPoolUpsertOne {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.ClearShadowQualifiedAt()
	})
}

// Exec executes the query.
func (u *OAuthPoolUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthPoolCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthPoolUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthPoolUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthPoolUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthPoolCreateBulk is the builder for creating many OAuthPool entities in bulk.
type OAuthPoolCreateBulk struct {
	config
	err      error
	builders []*OAuthPoolCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthPool entities in the database.
func (_c *OAuthPoolCreateBulk) Save(ctx context.Context) ([]*OAuthPool, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthPool, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthPoolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthPoolCreateBulk) SaveX(ctx context.Context) []*OAuthPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthPoolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthPoolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthPool.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthPoolCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthPoolUpsertBulk {
	_c.conflict = opts
	return &OAuthPoolUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthPoolCreateBulk) OnConflictColumns(columns ...string) *OAuthPoolUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthPoolUpsertBulk{
		create: _c,
	}
}

// OAuthPoolUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthPool nodes.
type OAuthPoolUpsertBulk struct {
	create *OAuthPoolCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthPoolUpsertBulk) UpdateNewValues() *OAuthPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthpool.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthPool.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthPoolUpsertBulk) Ignore() *OAuthPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthPoolUpsertBulk) DoNothing() *OAuthPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthPoolCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthPoolUpsertBulk) Update(set func(*OAuthPoolUpsert)) *OAuthPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthPoolUpsertBulk) SetUpdatedAt(v time.Time) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateUpdatedAt() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OAuthPoolUpsertBulk) SetDeletedAt(v time.Time) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateDeletedAt() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OAuthPoolUpsertBulk) ClearDeletedAt() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *OAuthPoolUpsertBulk) SetName(v string) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateName() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateName()
	})
}

// SetProvider sets the "provider" field.
func (u *OAuthPoolUpsertBulk) SetProvider(v string) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateProvider() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateProvider()
	})
}

// SetStatus sets the "status" field.
func (u *OAuthPoolUpsertBulk) SetStatus(v string) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateStatus() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateStatus()
	})
}

// SetMode sets the "mode" field.
func (u *OAuthPoolUpsertBulk) SetMode(v string) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateMode() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateMode()
	})
}

// SetEgressRouteID sets the "egress_route_id" field.
func (u *OAuthPoolUpsertBulk) SetEgressRouteID(v int64) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetEgressRouteID(v)
	})
}

// UpdateEgressRouteID sets the "egress_route_id" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateEgressRouteID() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateEgressRouteID()
	})
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (u *OAuthPoolUpsertBulk) SetAllowedOrigins(v []string) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetAllowedOrigins(v)
	})
}

// UpdateAllowedOrigins sets the "allowed_origins" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateAllowedOrigins() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateAllowedOrigins()
	})
}

// SetAllowedModels sets the "allowed_models" field.
func (u *OAuthPoolUpsertBulk) SetAllowedModels(v []string) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetAllowedModels(v)
	})
}

// UpdateAllowedModels sets the "allowed_models" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateAllowedModels() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateAllowedModels()
	})
}

// SetActiveCapsuleSetVersion sets the "active_capsule_set_version" field.
func (u *OAuthPoolUpsertBulk) SetActiveCapsuleSetVersion(v int64) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetActiveCapsuleSetVersion(v)
	})
}

// AddActiveCapsuleSetVersion adds v to the "active_capsule_set_version" field.
func (u *OAuthPoolUpsertBulk) AddActiveCapsuleSetVersion(v int64) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.AddActiveCapsuleSetVersion(v)
	})
}

// UpdateActiveCapsuleSetVersion sets the "active_capsule_set_version" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateActiveCapsuleSetVersion() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateActiveCapsuleSetVersion()
	})
}

// SetPreviousCapsuleSetVersion sets the "previous_capsule_set_version" field.
func (u *OAuthPoolUpsertBulk) SetPreviousCapsuleSetVersion(v int64) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetPreviousCapsuleSetVersion(v)
	})
}

// AddPreviousCapsuleSetVersion adds v to the "previous_capsule_set_version" field.
func (u *OAuthPoolUpsertBulk) AddPreviousCapsuleSetVersion(v int64) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.AddPreviousCapsuleSetVersion(v)
	})
}

// UpdatePreviousCapsuleSetVersion sets the "previous_capsule_set_version" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdatePreviousCapsuleSetVersion() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdatePreviousCapsuleSetVersion()
	})
}

// ClearPreviousCapsuleSetVersion clears the value of the "previous_capsule_set_version" field.
func (u *OAuthPoolUpsertBulk) ClearPreviousCapsuleSetVersion() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.ClearPreviousCapsuleSetVersion()
	})
}

// SetCompatibilityDigest sets the "compatibility_digest" field.
func (u *OAuthPoolUpsertBulk) SetCompatibilityDigest(v string) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetCompatibilityDigest(v)
	})
}

// UpdateCompatibilityDigest sets the "compatibility_digest" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateCompatibilityDigest() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateCompatibilityDigest()
	})
}

// SetSessionTTLSeconds sets the "session_ttl_seconds" field.
func (u *OAuthPoolUpsertBulk) SetSessionTTLSeconds(v int) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetSessionTTLSeconds(v)
	})
}

// AddSessionTTLSeconds adds v to the "session_ttl_seconds" field.
func (u *OAuthPoolUpsertBulk) AddSessionTTLSeconds(v int) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.AddSessionTTLSeconds(v)
	})
}

// UpdateSessionTTLSeconds sets the "session_ttl_seconds" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateSessionTTLSeconds() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateSessionTTLSeconds()
	})
}

// SetShadowStartedAt sets the "shadow_started_at" field.
func (u *OAuthPoolUpsertBulk) SetShadowStartedAt(v time.Time) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetShadowStartedAt(v)
	})
}

// UpdateShadowStartedAt sets the "shadow_started_at" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateShadowStartedAt() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateShadowStartedAt()
	})
}

// ClearShadowStartedAt clears the value of the "shadow_started_at" field.
func (u *OAuthPoolUpsertBulk) ClearShadowStartedAt() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.ClearShadowStartedAt()
	})
}

// SetShadowQualifiedAt sets the "shadow_qualified_at" field.
func (u *OAuthPoolUpsertBulk) SetShadowQualifiedAt(v time.Time) *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.SetShadowQualifiedAt(v)
	})
}

// UpdateShadowQualifiedAt sets the "shadow_qualified_at" field to the value that was provided on create.
func (u *OAuthPoolUpsertBulk) UpdateShadowQualifiedAt() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.UpdateShadowQualifiedAt()
	})
}

// ClearShadowQualifiedAt clears the value of the "shadow_qualified_at" field.
func (u *OAuthPoolUpsertBulk) ClearShadowQualifiedAt() *OAuthPoolUpsertBulk {
	return u.Update(func(s *OAuthPoolUpsert) {
		s.ClearShadowQualifiedAt()
	})
}

// Exec executes the query.
func (u *OAuthPoolUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthPoolCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthPoolCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthPoolUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
