// Code generated by ent, DO NOT EDIT.

package oauthcapsuleset

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the oauthcapsuleset type in the database.
	Label = "oauth_capsule_set"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPoolID holds the string denoting the pool_id field in the database.
	FieldPoolID = "pool_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldCompatibilityDigest holds the string denoting the compatibility_digest field in the database.
	FieldCompatibilityDigest = "compatibility_digest"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// EdgePool holds the string denoting the pool edge name in mutations.
	EdgePool = "pool"
	// Table holds the table name of the oauthcapsuleset in the database.
	Table = "oauth_capsule_sets"
	// PoolTable is the table that holds the pool relation/edge.
	PoolTable = "oauth_capsule_sets"
	// PoolInverseTable is the table name for the OAuthPool entity.
	// It exists in this package in order to avoid circular dependency with the "oauthpool" package.
	PoolInverseTable = "oauth_pools"
	// PoolColumn is the table column denoting the pool relation/edge.
	PoolColumn = "pool_id"
)

// Columns holds all SQL columns for oauthcapsuleset fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPoolID,
	FieldVersion,
	FieldCompatibilityDigest,
	FieldPayload,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CompatibilityDigestValidator is a validator for the "compatibility_digest" field. It is called by the builders before save.
	CompatibilityDigestValidator func(string) error
	// DefaultPayload holds the default value on creation for the "payload" field.
	DefaultPayload func() map[string]interface{}
)

// OrderOption defines the ordering options for the OAuthCapsuleSet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPoolID orders the results by the pool_id field.
func ByPoolID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoolID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByCompatibilityDigest orders the results by the compatibility_digest field.
func ByCompatibilityDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompatibilityDigest, opts...).ToFunc()
}

// ByPoolField orders the results by pool field.
func ByPoolField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPoolStep(), sql.OrderByField(field, opts...))
	}
}
func newPoolStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PoolInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PoolTable, PoolColumn),
	)
}
