// Code generated by ent, DO NOT EDIT.

package oauthcapsuleset

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dofastted/claude2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldUpdatedAt, v))
}

// PoolID applies equality check predicate on the "pool_id" field. It's identical to PoolIDEQ.
func PoolID(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldPoolID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldVersion, v))
}

// CompatibilityDigest applies equality check predicate on the "compatibility_digest" field. It's identical to CompatibilityDigestEQ.
func CompatibilityDigest(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldCompatibilityDigest, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLTE(FieldUpdatedAt, v))
}

// PoolIDEQ applies the EQ predicate on the "pool_id" field.
func PoolIDEQ(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldPoolID, v))
}

// PoolIDNEQ applies the NEQ predicate on the "pool_id" field.
func PoolIDNEQ(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNEQ(FieldPoolID, v))
}

// PoolIDIn applies the In predicate on the "pool_id" field.
func PoolIDIn(vs ...int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldIn(FieldPoolID, vs...))
}

// PoolIDNotIn applies the NotIn predicate on the "pool_id" field.
func PoolIDNotIn(vs ...int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNotIn(FieldPoolID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLTE(FieldVersion, v))
}

// CompatibilityDigestEQ applies the EQ predicate on the "compatibility_digest" field.
func CompatibilityDigestEQ(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEQ(FieldCompatibilityDigest, v))
}

// CompatibilityDigestNEQ applies the NEQ predicate on the "compatibility_digest" field.
func CompatibilityDigestNEQ(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNEQ(FieldCompatibilityDigest, v))
}

// CompatibilityDigestIn applies the In predicate on the "compatibility_digest" field.
func CompatibilityDigestIn(vs ...string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldIn(FieldCompatibilityDigest, vs...))
}

// CompatibilityDigestNotIn applies the NotIn predicate on the "compatibility_digest" field.
func CompatibilityDigestNotIn(vs ...string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldNotIn(FieldCompatibilityDigest, vs...))
}

// CompatibilityDigestGT applies the GT predicate on the "compatibility_digest" field.
func CompatibilityDigestGT(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGT(FieldCompatibilityDigest, v))
}

// CompatibilityDigestGTE applies the GTE predicate on the "compatibility_digest" field.
func CompatibilityDigestGTE(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldGTE(FieldCompatibilityDigest, v))
}

// CompatibilityDigestLT applies the LT predicate on the "compatibility_digest" field.
func CompatibilityDigestLT(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLT(FieldCompatibilityDigest, v))
}

// CompatibilityDigestLTE applies the LTE predicate on the "compatibility_digest" field.
func CompatibilityDigestLTE(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldLTE(FieldCompatibilityDigest, v))
}

// CompatibilityDigestContains applies the Contains predicate on the "compatibility_digest" field.
func CompatibilityDigestContains(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldContains(FieldCompatibilityDigest, v))
}

// CompatibilityDigestHasPrefix applies the HasPrefix predicate on the "compatibility_digest" field.
func CompatibilityDigestHasPrefix(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldHasPrefix(FieldCompatibilityDigest, v))
}

// CompatibilityDigestHasSuffix applies the HasSuffix predicate on the "compatibility_digest" field.
func CompatibilityDigestHasSuffix(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldHasSuffix(FieldCompatibilityDigest, v))
}

// CompatibilityDigestEqualFold applies the EqualFold predicate on the "compatibility_digest" field.
func CompatibilityDigestEqualFold(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldEqualFold(FieldCompatibilityDigest, v))
}

// CompatibilityDigestContainsFold applies the ContainsFold predicate on the "compatibility_digest" field.
func CompatibilityDigestContainsFold(v string) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.FieldContainsFold(FieldCompatibilityDigest, v))
}

// HasPool applies the HasEdge predicate on the "pool" edge.
func HasPool() predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PoolTable, PoolColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPoolWith applies the HasEdge predicate on the "pool" edge with a given conditions (other predicates).
func HasPoolWith(preds ...predicate.OAuthPool) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(func(s *sql.Selector) {
		step := newPoolStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthCapsuleSet) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthCapsuleSet) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthCapsuleSet) predicate.OAuthCapsuleSet {
	return predicate.OAuthCapsuleSet(sql.NotPredicates(p))
}
