// Code generated by ent, DO NOT EDIT.

package oauthpoolcredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dofastted/claude2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// PoolID applies equality check predicate on the "pool_id" field. It's identical to PoolIDEQ.
func PoolID(v int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldPoolID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldAccountID, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldState, v))
}

// CooldownUntil applies equality check predicate on the "cooldown_until" field. It's identical to CooldownUntilEQ.
func CooldownUntil(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldCooldownUntil, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// PoolIDEQ applies the EQ predicate on the "pool_id" field.
func PoolIDEQ(v int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldPoolID, v))
}

// PoolIDNEQ applies the NEQ predicate on the "pool_id" field.
func PoolIDNEQ(v int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNEQ(FieldPoolID, v))
}

// PoolIDIn applies the In predicate on the "pool_id" field.
func PoolIDIn(vs ...int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldIn(FieldPoolID, vs...))
}

// PoolIDNotIn applies the NotIn predicate on the "pool_id" field.
func PoolIDNotIn(vs ...int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNotIn(FieldPoolID, vs...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNotIn(FieldAccountID, vs...))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldContainsFold(FieldState, v))
}

// CooldownUntilEQ applies the EQ predicate on the "cooldown_until" field.
func CooldownUntilEQ(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldEQ(FieldCooldownUntil, v))
}

// CooldownUntilNEQ applies the NEQ predicate on the "cooldown_until" field.
func CooldownUntilNEQ(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNEQ(FieldCooldownUntil, v))
}

// CooldownUntilIn applies the In predicate on the "cooldown_until" field.
func CooldownUntilIn(vs ...time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldIn(FieldCooldownUntil, vs...))
}

// CooldownUntilNotIn applies the NotIn predicate on the "cooldown_until" field.
func CooldownUntilNotIn(vs ...time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNotIn(FieldCooldownUntil, vs...))
}

// CooldownUntilGT applies the GT predicate on the "cooldown_until" field.
func CooldownUntilGT(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGT(FieldCooldownUntil, v))
}

// CooldownUntilGTE applies the GTE predicate on the "cooldown_until" field.
func CooldownUntilGTE(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldGTE(FieldCooldownUntil, v))
}

// CooldownUntilLT applies the LT predicate on the "cooldown_until" field.
func CooldownUntilLT(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLT(FieldCooldownUntil, v))
}

// CooldownUntilLTE applies the LTE predicate on the "cooldown_until" field.
func CooldownUntilLTE(v time.Time) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldLTE(FieldCooldownUntil, v))
}

// CooldownUntilIsNil applies the IsNil predicate on the "cooldown_until" field.
func CooldownUntilIsNil() predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldIsNull(FieldCooldownUntil))
}

// CooldownUntilNotNil applies the NotNil predicate on the "cooldown_until" field.
func CooldownUntilNotNil() predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.FieldNotNull(FieldCooldownUntil))
}

// HasPool applies the HasEdge predicate on the "pool" edge.
func HasPool() predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PoolTable, PoolColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPoolWith applies the HasEdge predicate on the "pool" edge with a given conditions (other predicates).
func HasPoolWith(preds ...predicate.OAuthPool) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(func(s *sql.Selector) {
		step := newPoolStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthPoolCredential) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthPoolCredential) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthPoolCredential) predicate.OAuthPoolCredential {
	return predicate.OAuthPoolCredential(sql.NotPredicates(p))
}
